export type CultureDestinationDefinition = {
  slug: string;
  /** Large hero heading (e.g. Kerala) */
  heroTitle: string;
  /** Small pill above title */
  heroBadge: string;
  tagline: string;
  heroImage: string;
  /** Lowercase tokens matched in titles, tags, culture & language fields */
  matchTerms: string[];
  /** Shown as culture chips (subset of taxonomy; also merged from live events) */
  cultureCommunities: string[];
  languages: string[];
  /**
   * When the viewer is in this country, boost events that also match `originKeywords`
   * (e.g. India + kerala/malayalam for homeland + travel).
   */
  originCountryHint?: string;
  originKeywords?: string[];
  /** Web / share path (no host), e.g. /kerala */
  publicPath: string;
  metaDescription: string;
};

const HERO = {
  kerala:
    'https://images.unsplash.com/photo-1596178065887-1198b6148b2b?auto=format&fit=crop&w=2000&q=90',
  india: 'https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=2000&q=90',
  festival:
    'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=2000&q=90',
  city: 'https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?auto=format&fit=crop&w=2000&q=90',
  dance: 'https://images.unsplash.com/photo-1504609773096-104ff2c73ba4?auto=format&fit=crop&w=2000&q=90',
  food: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?auto=format&fit=crop&w=2000&q=90',
  globe: 'https://images.unsplash.com/photo-1526778548025-fa2f459cd5c1?auto=format&fit=crop&w=2000&q=90',
} as const;

export const CULTURE_DESTINATIONS: Record<string, CultureDestinationDefinition> = {
  kerala: {
    slug: 'kerala',
    heroTitle: 'Kerala',
    heroBadge: 'MALAYALEE WORLD',
    tagline: 'Onam to overseas — festivals, film, food, and community wherever Malayalam speakers gather.',
    heroImage: HERO.kerala,
    matchTerms: [
      'kerala',
      'malayali',
      'malayalee',
      'malayalie',
      'malayalam',
      'onam',
      'vishu',
      'thiruvananthapuram',
      'kochi',
      'kozhikode',
      'thrissur',
      'moplah',
      'mallu',
    ],
    cultureCommunities: ['Malayalam', 'Malayalee', 'Kerala', 'South Indian', 'NRI Malayali', 'Gulf Malayali'],
    languages: ['Malayalam', 'English', 'Hindi'],
    originCountryHint: 'India',
    originKeywords: ['kerala', 'malayalam', 'malayali', 'malayalee', 'thiruvananthapuram', 'kochi'],
    publicPath: '/kerala',
    metaDescription:
      'Discover Kerala and Malayalee events worldwide — filter by country and state, or browse the full diaspora hub.',
  },

  gujarati: {
    slug: 'gujarati',
    heroTitle: 'Gujarati',
    heroBadge: 'GUJARAT & DIASPORA',
    tagline: 'Navratri nights, business networks, and hometown ties from Ahmedabad to Auckland.',
    heroImage: HERO.festival,
    matchTerms: [
      'gujarati',
      'gujarat',
      'ahmedabad',
      'surat',
      'vadodara',
      'rajkot',
      'bhavnagar',
      'kathiyawadi',
      'kathiyawad',
      'garba',
      'dandiya',
      'navratri',
    ],
    cultureCommunities: ['Gujarati', 'Gujarat', 'Patidar', 'NRI Gujarati'],
    languages: ['Gujarati', 'Hindi', 'English'],
    originCountryHint: 'India',
    originKeywords: ['gujarat', 'gujarati', 'ahmedabad', 'surat', 'vadodara'],
    publicPath: '/culture/gujarati',
    metaDescription:
      'Gujarati culture, language, and community events — search one country or the worldwide hub.',
  },

  punjabi: {
    slug: 'punjabi',
    heroTitle: 'Punjabi',
    heroBadge: 'PUNJAB & DIASPORA',
    tagline: 'Bhangra, gurdwaras, and festivals from Lahore–Amritsar lines to every major city.',
    heroImage: HERO.dance,
    matchTerms: [
      'punjabi',
      'punjab',
      'sikh',
      'gurdwara',
      'gurudwara',
      'bhangra',
      'amritsar',
      'chandigarh',
      'ludhiana',
      'jalandhar',
      'patiala',
      'phagwara',
      'vaisakhi',
      'baisakhi',
    ],
    cultureCommunities: ['Punjabi', 'Sikh', 'Punjab', 'NRI Punjabi'],
    languages: ['Punjabi', 'Hindi', 'English'],
    originCountryHint: 'India',
    originKeywords: ['punjab', 'punjabi', 'sikh', 'amritsar', 'bhangra'],
    publicPath: '/culture/punjabi',
    metaDescription: 'Punjabi and Sikh community events worldwide — by country, state, or full diaspora.',
  },

  tamil: {
    slug: 'tamil',
    heroTitle: 'Tamil',
    heroBadge: 'TAMIL WORLD',
    tagline: 'Pongal to film nights — Chennai, Jaffna, and Tamil diaspora everywhere.',
    heroImage: HERO.india,
    matchTerms: [
      'tamil',
      'tamizh',
      'tamil nadu',
      'chennai',
      'coimbatore',
      'madurai',
      'jaffna',
      'eelam',
      'pongal',
      'thai pongal',
      'kollywood',
    ],
    cultureCommunities: ['Tamil', 'Tamil Nadu', 'Sri Lankan Tamil', 'NRI Tamil'],
    languages: ['Tamil', 'English'],
    originCountryHint: 'India',
    originKeywords: ['tamil', 'chennai', 'tamil nadu', 'pongal'],
    publicPath: '/culture/tamil',
    metaDescription: 'Tamil language and culture events — filter by your country or browse globally.',
  },

  telugu: {
    slug: 'telugu',
    heroTitle: 'Telugu',
    heroBadge: 'ANDHRA & TELANGANA',
    tagline: 'Ugadi to overseas screenings — Telugu voices across continents.',
    heroImage: HERO.festival,
    matchTerms: [
      'telugu',
      'andhra',
      'telangana',
      'hyderabad',
      'vijayawada',
      'visakhapatnam',
      'vizag',
      'guntur',
      'tollywood',
      'ugadi',
      'sankranti',
    ],
    cultureCommunities: ['Telugu', 'Andhra', 'Telangana', 'NRI Telugu'],
    languages: ['Telugu', 'English', 'Hindi'],
    originCountryHint: 'India',
    originKeywords: ['telugu', 'hyderabad', 'telangana', 'andhra'],
    publicPath: '/culture/telugu',
    metaDescription: 'Telugu community events and festivals — scoped to your country or worldwide.',
  },

  bengali: {
    slug: 'bengali',
    heroTitle: 'Bengali',
    heroBadge: 'BANGLA & BEYOND',
    tagline: 'Durga Puja, poetry, and film — Kolkata, Dhaka, and diaspora halls worldwide.',
    heroImage: HERO.festival,
    matchTerms: [
      'bengali',
      'bangla',
      'bangladesh',
      'kolkata',
      'calcutta',
      'dhaka',
      'chittagong',
      'sylhet',
      'durga puja',
      'pohela boishakh',
      'noboborsho',
    ],
    cultureCommunities: ['Bengali', 'Bangladeshi', 'West Bengal', 'NRI Bengali'],
    languages: ['Bengali', 'Bangla', 'English'],
    originCountryHint: 'India',
    originKeywords: ['bengali', 'bangla', 'kolkata', 'durga puja'],
    publicPath: '/culture/bengali',
    metaDescription: 'Bengali and Bangla cultural events — by region or full diaspora search.',
  },

  marathi: {
    slug: 'marathi',
    heroTitle: 'Marathi',
    heroBadge: 'MAHARASHTRA',
    tagline: 'Ganesh Utsav, theatre, and community from Mumbai to the global Maharashtrian network.',
    heroImage: HERO.city,
    matchTerms: [
      'marathi',
      'maharashtra',
      'mumbai',
      'pune',
      'nagpur',
      'nashik',
      'ganesh',
      'ganpati',
      'gudi padwa',
    ],
    cultureCommunities: ['Marathi', 'Maharashtra', 'NRI Marathi'],
    languages: ['Marathi', 'Hindi', 'English'],
    originCountryHint: 'India',
    originKeywords: ['marathi', 'maharashtra', 'mumbai', 'pune'],
    publicPath: '/culture/marathi',
    metaDescription: 'Marathi culture and events worldwide — filter by country and state.',
  },

  kannada: {
    slug: 'kannada',
    heroTitle: 'Kannada',
    heroBadge: 'KARNATAKA',
    tagline: 'From Bengaluru tech meets to Yakshagana — Kannadiga community everywhere.',
    heroImage: HERO.india,
    matchTerms: [
      'kannada',
      'kannadiga',
      'karnataka',
      'bengaluru',
      'bangalore',
      'mysuru',
      'mysore',
      'mangaluru',
      'mangalore',
      'hubli',
      'udupi',
    ],
    cultureCommunities: ['Kannada', 'Karnataka', 'NRI Kannadiga'],
    languages: ['Kannada', 'English'],
    originCountryHint: 'India',
    originKeywords: ['kannada', 'karnataka', 'bengaluru', 'bangalore'],
    publicPath: '/culture/kannada',
    metaDescription: 'Kannada language and Karnataka-rooted events — local scope or diaspora hub.',
  },

  odia: {
    slug: 'odia',
    heroTitle: 'Odia',
    heroBadge: 'ODISHA',
    tagline: 'Rath Yatra to diaspora societies — Odia language and heritage worldwide.',
    heroImage: HERO.festival,
    matchTerms: ['odia', 'oriya', 'odisha', 'orissa', 'bhubaneswar', 'cuttack', 'rath yatra', 'jagannath'],
    cultureCommunities: ['Odia', 'Odisha', 'NRI Odia'],
    languages: ['Odia', 'Oriya', 'English'],
    originCountryHint: 'India',
    originKeywords: ['odia', 'odisha', 'oriya', 'bhubaneswar'],
    publicPath: '/culture/odia',
    metaDescription: 'Odia culture and community events — search your country or the world.',
  },

  hindi: {
    slug: 'hindi',
    heroTitle: 'Hindi & North Indian',
    heroBadge: 'HINDI HEARTLAND',
    tagline: 'Bollywood nights, Diwali melas, and Hindi-Urdu cultural life in every city.',
    heroImage: HERO.dance,
    matchTerms: [
      'hindi',
      'bollywood',
      'diwali',
      'holi',
      'delhi',
      'lucknow',
      'jaipur',
      'kanpur',
      'varanasi',
      'north indian',
      'urdu',
      'hindustani',
    ],
    cultureCommunities: ['Hindi', 'North Indian', 'Bollywood', 'NRI Hindi'],
    languages: ['Hindi', 'Urdu', 'English'],
    originCountryHint: 'India',
    originKeywords: ['hindi', 'bollywood', 'delhi', 'diwali'],
    publicPath: '/culture/hindi',
    metaDescription: 'Hindi-language and North Indian cultural events — scoped to you or worldwide.',
  },

  filipino: {
    slug: 'filipino',
    heroTitle: 'Filipino',
    heroBadge: 'PINOY WORLDWIDE',
    tagline: 'Barrio fiestas, bayanihan, and Tagalog voices from Manila to the Middle East and beyond.',
    heroImage: HERO.food,
    matchTerms: [
      'filipino',
      'pinoy',
      'philippines',
      'manila',
      'cebu',
      'davao',
      'tagalog',
      'ilocano',
      'cebuano',
      'barrio fiesta',
    ],
    cultureCommunities: ['Filipino', 'Pinoy', 'Philippines'],
    languages: ['Tagalog', 'Filipino', 'English'],
    originCountryHint: 'Philippines',
    originKeywords: ['filipino', 'pinoy', 'philippines', 'tagalog'],
    publicPath: '/culture/filipino',
    metaDescription: 'Filipino community events — all across your country or the global hub.',
  },

  vietnamese: {
    slug: 'vietnamese',
    heroTitle: 'Vietnamese',
    heroBadge: 'VIỆT KIỀU & LOCAL',
    tagline: 'Tết, community halls, and Vietnamese culture in every host country.',
    heroImage: HERO.food,
    matchTerms: [
      'vietnamese',
      'vietnam',
      'tet',
      'tết',
      'ho chi minh',
      'saigon',
      'hanoi',
      'viet kieu',
      'việt',
    ],
    cultureCommunities: ['Vietnamese', 'Vietnam', 'Viet Kieu'],
    languages: ['Vietnamese', 'English'],
    originCountryHint: 'Vietnam',
    originKeywords: ['vietnamese', 'vietnam', 'tet', 'saigon'],
    publicPath: '/culture/vietnamese',
    metaDescription: 'Vietnamese cultural events — filter by country and region or browse worldwide.',
  },

  korean: {
    slug: 'korean',
    heroTitle: 'Korean',
    heroBadge: 'HALLYU & COMMUNITY',
    tagline: 'K-pop, film, language exchanges, and Korean diaspora meetups.',
    heroImage: HERO.city,
    matchTerms: ['korean', 'korea', 'seoul', 'busan', 'hallyu', 'k-pop', 'kpop', 'hangul', 'chuseok'],
    cultureCommunities: ['Korean', 'South Korean', 'K-Drama'],
    languages: ['Korean', 'English'],
    originCountryHint: 'South Korea',
    originKeywords: ['korean', 'korea', 'seoul', 'hallyu'],
    publicPath: '/culture/korean',
    metaDescription: 'Korean culture and community events — your country first or global listings.',
  },

  lebanese: {
    slug: 'lebanese',
    heroTitle: 'Lebanese & Arab',
    heroBadge: 'LEVANT & DIASPORA',
    tagline: 'Food, dabke, and community from Beirut to every Lebanese quarter.',
    heroImage: HERO.festival,
    matchTerms: ['lebanese', 'lebanon', 'beirut', 'levant', 'arab', 'arabic', 'dabke', 'druze', 'maronite'],
    cultureCommunities: ['Lebanese', 'Arab', 'Levantine'],
    languages: ['Arabic', 'English', 'French'],
    originCountryHint: 'Lebanon',
    originKeywords: ['lebanese', 'lebanon', 'beirut', 'arabic'],
    publicPath: '/culture/lebanese',
    metaDescription: 'Lebanese and Levant-rooted events — narrow to your area or open worldwide.',
  },

  persian: {
    slug: 'persian',
    heroTitle: 'Persian & Iranian',
    heroBadge: 'NOWRUZ & BEYOND',
    tagline: 'Nowruz, poetry, and Iranian diaspora gatherings.',
    heroImage: HERO.globe,
    matchTerms: ['persian', 'iranian', 'iran', 'tehran', 'farsi', 'nowruz', 'norooz', 'norouz', 'shiraz', 'isfahan'],
    cultureCommunities: ['Persian', 'Iranian', 'Farsi'],
    languages: ['Persian', 'Farsi', 'English'],
    originCountryHint: 'Iran',
    originKeywords: ['persian', 'iranian', 'farsi', 'nowruz'],
    publicPath: '/culture/persian',
    metaDescription: 'Persian-language and Iranian cultural events — by country or diaspora-wide.',
  },

  somali: {
    slug: 'somali',
    heroTitle: 'Somali',
    heroBadge: 'SOMALI DIASPORA',
    tagline: 'Community, poetry, and heritage from the Horn of Africa to global cities.',
    heroImage: HERO.globe,
    matchTerms: ['somali', 'somalia', 'mogadishu', 'hargeisa', 'somaliland', 'ogaden', 'xamar'],
    cultureCommunities: ['Somali', 'Somalia', 'East African'],
    languages: ['Somali', 'English', 'Arabic'],
    originCountryHint: 'Somalia',
    originKeywords: ['somali', 'somalia', 'mogadishu'],
    publicPath: '/culture/somali',
    metaDescription: 'Somali community and cultural events — scoped locally or worldwide.',
  },

  ethiopian: {
    slug: 'ethiopian',
    heroTitle: 'Ethiopian & Eritrean',
    heroBadge: 'HABESHA',
    tagline: 'Coffee ceremonies, Timkat, and Habesha community life abroad.',
    heroImage: HERO.food,
    matchTerms: [
      'ethiopian',
      'ethiopia',
      'addis',
      'addis ababa',
      'eritrean',
      'eritrea',
      'habesha',
      'amharic',
      'tigrinya',
      'timkat',
    ],
    cultureCommunities: ['Ethiopian', 'Eritrean', 'Habesha', 'Amharic'],
    languages: ['Amharic', 'Tigrinya', 'English'],
    originCountryHint: 'Ethiopia',
    originKeywords: ['ethiopian', 'habesha', 'amharic', 'addis'],
    publicPath: '/culture/ethiopian',
    metaDescription: 'Ethiopian and Eritrean cultural events — filter by host country or browse all.',
  },

  nigerian: {
    slug: 'nigerian',
    heroTitle: 'Nigerian & West African',
    heroBadge: 'NOLLYWOOD & COMMUNITY',
    tagline: 'Afrobeats, film, and hometown unions from Lagos to London and beyond.',
    heroImage: HERO.dance,
    matchTerms: [
      'nigerian',
      'nigeria',
      'lagos',
      'abuja',
      'ibadan',
      'yoruba',
      'igbo',
      'hausa',
      'afrobeats',
      'nollywood',
      'west african',
    ],
    cultureCommunities: ['Nigerian', 'Yoruba', 'Igbo', 'Hausa', 'West African'],
    languages: ['English', 'Yoruba', 'Igbo', 'Hausa'],
    originCountryHint: 'Nigeria',
    originKeywords: ['nigerian', 'nigeria', 'lagos', 'yoruba', 'igbo'],
    publicPath: '/culture/nigerian',
    metaDescription: 'Nigerian and West African events — your country or full diaspora listings.',
  },

  mandarin: {
    slug: 'mandarin',
    heroTitle: 'Chinese (Mandarin)',
    heroBadge: 'HUAREN COMMUNITY',
    tagline: 'Lunar New Year, language corners, and Mandarin-speaking community worldwide.',
    heroImage: HERO.festival,
    matchTerms: [
      'mandarin',
      'chinese',
      'china',
      'beijing',
      'shanghai',
      'guangzhou',
      'shenzhen',
      'taiwan',
      'taipei',
      'cantonese',
      'huaren',
      'lunar new year',
      'chinese new year',
    ],
    cultureCommunities: ['Chinese', 'Mandarin', 'Cantonese', 'Taiwanese', 'Huaren'],
    languages: ['Mandarin', 'Cantonese', 'English'],
    originCountryHint: 'China',
    originKeywords: ['mandarin', 'chinese', 'shanghai', 'beijing'],
    publicPath: '/culture/mandarin',
    metaDescription: 'Mandarin and Chinese community events — by country, region, or worldwide hub.',
  },

  japanese: {
    slug: 'japanese',
    heroTitle: 'Japanese',
    heroBadge: 'NIHON & DIASPORA',
    tagline: 'Matsuri, film, language exchange, and Japanese community abroad.',
    heroImage: HERO.city,
    matchTerms: ['japanese', 'japan', 'tokyo', 'osaka', 'kyoto', 'nihon', 'nihongo', 'matsuri', 'bon odori'],
    cultureCommunities: ['Japanese', 'Japan', 'Nihonjin'],
    languages: ['Japanese', 'English'],
    originCountryHint: 'Japan',
    originKeywords: ['japanese', 'japan', 'tokyo', 'nihongo'],
    publicPath: '/culture/japanese',
    metaDescription: 'Japanese cultural events — local to your country or global.',
  },

  mexican: {
    slug: 'mexican',
    heroTitle: 'Mexican & Chicano',
    heroBadge: 'MÉXICO & DIASPORA',
    tagline: 'Día de los Muertos, música, and community from CDMX to every barrio.',
    heroImage: HERO.festival,
    matchTerms: [
      'mexican',
      'mexico',
      'cdmx',
      'ciudad de mexico',
      'guadalajara',
      'monterrey',
      'chicano',
      'chicana',
      'latino',
      'latinx',
      'hispanic',
    ],
    cultureCommunities: ['Mexican', 'Chicano', 'Latino', 'Latin American'],
    languages: ['Spanish', 'English'],
    originCountryHint: 'Mexico',
    originKeywords: ['mexican', 'mexico', 'chicano', 'cdmx'],
    publicPath: '/culture/mexican',
    metaDescription: 'Mexican and Chicano cultural events — filter by host country or browse widely.',
  },

  greek: {
    slug: 'greek',
    heroTitle: 'Greek & Cypriot',
    heroBadge: 'HELLENIC',
    tagline: 'Glendia, Orthodox feasts, and Hellenic community worldwide.',
    heroImage: HERO.globe,
    matchTerms: ['greek', 'greece', 'athens', 'thessaloniki', 'cypriot', 'cyprus', 'hellenic', 'ελλην'],
    cultureCommunities: ['Greek', 'Cypriot', 'Hellenic'],
    languages: ['Greek', 'English'],
    originCountryHint: 'Greece',
    originKeywords: ['greek', 'greece', 'athens', 'hellenic'],
    publicPath: '/culture/greek',
    metaDescription: 'Greek and Cypriot community events — scoped to you or diaspora-wide.',
  },

  italian: {
    slug: 'italian',
    heroTitle: 'Italian',
    heroBadge: 'ITALIA & DIASPORA',
    tagline: 'Feste, calcio clubs, and Italian community from Rome to Melbourne.',
    heroImage: HERO.food,
    matchTerms: ['italian', 'italy', 'roma', 'rome', 'milan', 'milano', 'naples', 'napoli', 'sicilian', 'sicily'],
    cultureCommunities: ['Italian', 'Italo-Australian', 'Sicilian'],
    languages: ['Italian', 'English'],
    originCountryHint: 'Italy',
    originKeywords: ['italian', 'italy', 'rome', 'sicilian'],
    publicPath: '/culture/italian',
    metaDescription: 'Italian cultural events — by country and region or full hub.',
  },

  ukrainian: {
    slug: 'ukrainian',
    heroTitle: 'Ukrainian',
    heroBadge: 'УКРАЇНА & DIASPORA',
    tagline: 'Vyshyvanka days, community aid, and Ukrainian voices everywhere.',
    heroImage: HERO.globe,
    matchTerms: ['ukrainian', 'ukraine', 'kyiv', 'kiev', 'lviv', 'odesa', 'vyshyvanka', 'україн'],
    cultureCommunities: ['Ukrainian', 'Ukraine'],
    languages: ['Ukrainian', 'English'],
    originCountryHint: 'Ukraine',
    originKeywords: ['ukrainian', 'ukraine', 'kyiv'],
    publicPath: '/culture/ukrainian',
    metaDescription: 'Ukrainian community and cultural events — local scope or worldwide.',
  },
};

export function getCultureDestination(slug: string): CultureDestinationDefinition | null {
  const key = slug.trim().toLowerCase();
  return CULTURE_DESTINATIONS[key] ?? null;
}

/** Ordered list for menus / SEO sitemaps (optional). */
export function listCultureDestinationSlugs(): string[] {
  return Object.keys(CULTURE_DESTINATIONS).sort();
}
