import { CultureTokens } from '@/constants/theme';

export interface InterestCategory {
  id: string;
  title: string;
  accentColor: string;
  softColor: string;
  interests: string[];
}

export const popularInterestsSydney: string[] = [
  'Cultural Festivals',
  'Indian Events',
  'Live Music',
  'Food Festivals',
  'Business Networking',
  'Family-Friendly Events',
  'Local Council Events',
  'Workshops',
  'Free Events',
  'Outdoor Events',
];

export const interestCategories: InterestCategory[] = [
  {
    id: 'cultural',
    title: 'Cultural & Community',
    accentColor: CultureTokens.gold,
    softColor: CultureTokens.eventSoft,
    interests: [
      'Cultural Festivals',
      'Indian Events',
      'South Asian Events',
      'Multicultural Events',
      'Religious & Spiritual Gatherings',
      'Community Meetups',
      'Language & Heritage',
      'Traditional Dance',
      'Classical Music',
      'Folk Arts',
      'Temple Events',
      'Onam Celebrations',
      'Diwali Celebrations',
      'Eid Festivals',
      'Christmas Events',
      'Australia Day Events',
    ],
  },
  {
    id: 'arts',
    title: 'Arts & Entertainment',
    accentColor: CultureTokens.coral,
    softColor: CultureTokens.artistSoft,
    interests: [
      'Live Music',
      'DJ & Nightlife',
      'Theatre',
      'Comedy Shows',
      'Cinema & Film Screenings',
      'Rooftop Movies',
      'Art Exhibitions',
      'Poetry & Open Mic',
      'Fashion Shows',
      'Talent Showcases',
      'Cultural Performances',
    ],
  },
  {
    id: 'food',
    title: 'Food & Lifestyle',
    accentColor: CultureTokens.gold,
    softColor: CultureTokens.movieSoft,
    interests: [
      'Food Festivals',
      'Street Food',
      'Indian Restaurants',
      'New Restaurant Openings',
      'Coffee & Cafés',
      'Dessert Spots',
      'Food Deals',
      'Cooking Workshops',
      'Wine Tastings',
      'Pop-up Markets',
    ],
  },
  {
    id: 'business',
    title: 'Business & Networking',
    accentColor: CultureTokens.indigo,
    softColor: CultureTokens.communitySoft,
    interests: [
      'Startup Events',
      'Business Networking',
      'Professional Meetups',
      'Cultural Entrepreneurs',
      'Community Leaders',
      'Investment Events',
      'Tech Events',
      'Workshops & Skill Building',
      'Conferences',
      'Career Events',
    ],
  },
  {
    id: 'family',
    title: 'Family & Kids',
    accentColor: CultureTokens.community,
    softColor: CultureTokens.communitySoft,
    interests: [
      'Family-Friendly Events',
      'Kids Activities',
      'School Holiday Programs',
      'Cultural Education',
      'Dance Classes',
      'Sports for Kids',
      'Outdoor Family Events',
    ],
  },
  {
    id: 'civic',
    title: 'Civic & Local',
    accentColor: CultureTokens.teal,
    softColor: CultureTokens.venueSoft,
    interests: [
      'Local Council Events',
      'Community Centres',
      'Public Library Events',
      'Local Markets',
      'Fitness & Gyms',
      'Public Pools',
      'Outdoor Cinema',
      'Volunteering',
      'Clean-Up Days',
    ],
  },
  {
    id: 'wellness',
    title: 'Wellness & Spiritual',
    accentColor: CultureTokens.teal,
    softColor: CultureTokens.venueSoft,
    interests: [
      'Yoga',
      'Meditation',
      'Ayurveda',
      'Temple Visits',
      'Church Gatherings',
      'Mosque Events',
      'Health & Fitness',
      'Running Clubs',
    ],
  },
  {
    id: 'format',
    title: 'Format Signals',
    accentColor: CultureTokens.gold,
    softColor: CultureTokens.movieSoft,
    interests: [
      'Free Events',
      'Paid Events',
      'Early Access',
      'VIP Events',
      'Workshops',
      'Festivals',
      'Exhibitions',
      'Outdoor Events',
      'Indoor Events',
    ],
  },
];

const iconByInterestEntries: [string, string][] = [
  ['Cultural Festivals', 'sparkles'],
  ['Indian Events', 'globe'],
  ['South Asian Events', 'earth'],
  ['Multicultural Events', 'people-circle'],
  ['Religious & Spiritual Gatherings', 'leaf'],
  ['Community Meetups', 'people'],
  ['Language & Heritage', 'chatbubbles'],
  ['Traditional Dance', 'body'],
  ['Classical Music', 'musical-notes'],
  ['Folk Arts', 'color-palette'],
  ['Temple Events', 'business'],
  ['Onam Celebrations', 'flower'],
  ['Diwali Celebrations', 'flame'],
  ['Eid Festivals', 'moon'],
  ['Christmas Events', 'gift'],
  ['Australia Day Events', 'flag'],

  ['Live Music', 'musical-notes'],
  ['DJ & Nightlife', 'radio'],
  ['Theatre', 'film'],
  ['Comedy Shows', 'happy'],
  ['Cinema & Film Screenings', 'videocam'],
  ['Rooftop Movies', 'tv'],
  ['Art Exhibitions', 'images'],
  ['Poetry & Open Mic', 'mic'],
  ['Fashion Shows', 'shirt'],
  ['Talent Showcases', 'trophy'],
  ['Cultural Performances', 'aperture'],

  ['Food Festivals', 'restaurant'],
  ['Street Food', 'fast-food'],
  ['Indian Restaurants', 'restaurant'],
  ['New Restaurant Openings', 'storefront'],
  ['Coffee & Cafés', 'cafe'],
  ['Dessert Spots', 'ice-cream'],
  ['Food Deals', 'pricetag'],
  ['Cooking Workshops', 'nutrition'],
  ['Wine Tastings', 'wine'],
  ['Pop-up Markets', 'cart'],

  ['Startup Events', 'rocket'],
  ['Business Networking', 'briefcase'],
  ['Professional Meetups', 'people'],
  ['Cultural Entrepreneurs', 'bulb'],
  ['Community Leaders', 'ribbon'],
  ['Investment Events', 'cash'],
  ['Tech Events', 'hardware-chip'],
  ['Workshops & Skill Building', 'construct'],
  ['Conferences', 'podium'],
  ['Career Events', 'id-card'],

  ['Family-Friendly Events', 'home'],
  ['Kids Activities', 'happy'],
  ['School Holiday Programs', 'school'],
  ['Cultural Education', 'book'],
  ['Dance Classes', 'walk'],
  ['Sports for Kids', 'football'],
  ['Outdoor Family Events', 'sunny'],

  ['Local Council Events', 'business'],
  ['Community Centres', 'people-circle'],
  ['Public Library Events', 'library'],
  ['Local Markets', 'basket'],
  ['Fitness & Gyms', 'barbell'],
  ['Public Pools', 'water'],
  ['Outdoor Cinema', 'tv'],
  ['Volunteering', 'heart'],
  ['Clean-Up Days', 'leaf'],

  ['Yoga', 'body'],
  ['Meditation', 'moon'],
  ['Ayurveda', 'leaf'],
  ['Temple Visits', 'business'],
  ['Church Gatherings', 'book'],
  ['Mosque Events', 'moon'],
  ['Health & Fitness', 'fitness'],
  ['Running Clubs', 'walk'],

  ['Free Events', 'pricetag'],
  ['Paid Events', 'card'],
  ['Early Access', 'time'],
  ['VIP Events', 'diamond'],
  ['Workshops', 'construct'],
  ['Festivals', 'sparkles'],
  ['Exhibitions', 'images'],
  ['Outdoor Events', 'sunny'],
  ['Indoor Events', 'home'],
];

export const interestIcons: Record<string, string> = Object.fromEntries(iconByInterestEntries);
export const interests: string[] = interestCategories.flatMap((category) => category.interests);
