#!/usr/bin/env ts-node
/**
 * Firestore Seed Script — CulturePass
 *
 * Populates the Firestore database with initial events, profiles, communities,
 * businesses, traditional lands data, and indigenous spotlights.
 *
 * Run from the `functions/` directory:
 *   npx ts-node scripts/seed-firestore.ts
 *
 * To clear existing data first:
 *   npx ts-node scripts/seed-firestore.ts --clear
 *
 * Prerequisites:
 *   - firebase login (or GOOGLE_APPLICATION_CREDENTIALS env var)
 *   - GOOGLE_CLOUD_PROJECT env var OR set projectId below
 */

import * as admin from 'firebase-admin';

const PROJECT_ID = process.env.GOOGLE_CLOUD_PROJECT ?? 'culturepassau';
const CLEAR = process.argv.includes('--clear');

if (!admin.apps.length) {
  admin.initializeApp({
    credential: admin.credential.applicationDefault(),
    projectId: PROJECT_ID,
  });
}

const db = admin.firestore();
const now = new Date().toISOString();

const soon = (daysFromNow: number): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysFromNow);
  return d.toISOString().slice(0, 10);
};

// ---------------------------------------------------------------------------
// Events — 40+ across AU, NZ, UAE, UK, Canada
// Includes council-partnered events and multicultural festivals
// ---------------------------------------------------------------------------

const EVENTS = [
  // ── SYDNEY ─────────────────────────────────────────────────────────────────
  {
    title: 'Sydney Kerala Cultural Festival 2026',
    description: 'The biggest Malayalam cultural gathering in the Southern Hemisphere. Live Kathakali dance, traditional cuisine, and community awards. Supported by City of Sydney Council. Families welcome.',
    communityId: 'Malayalam',
    venue: 'Darling Harbour Convention Centre',
    address: '14 Darling Dr, Sydney NSW 2000',
    date: soon(14),
    time: '10:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1598300056393-4aac492f4344?w=800',
    imageColor: '#E8472A',
    cultureTag: ['Kerala', 'Malayalam', 'South Indian'],
    tags: ['festival', 'culture', 'family', 'dance'],
    category: 'Festival',
    priceTier: 'mid',
    priceCents: 2500,
    priceLabel: '$25',
    isFree: false,
    isFeatured: true,
    capacity: 2000,
    attending: 847,
    organizerId: 'seed-org-1',
    organizer: 'Kerala Community Sydney',
    organizerReputationScore: 92,
    status: 'published',
    cpid: 'CP-E-KCFSYD',
    councilPartner: 'City of Sydney',
    tiers: [
      { name: 'General', priceCents: 2500, available: 1200 },
      { name: 'Family Pack (4)', priceCents: 8000, available: 200 },
      { name: 'VIP', priceCents: 7500, available: 50 },
    ],
  },
  {
    title: 'Tamil Pongal Celebration — Sydney',
    description: 'Join us to celebrate the harvest festival of Pongal with traditional kolam art, music, and a bonfire ceremony. Co-hosted by Parramatta City Council.',
    communityId: 'Tamil',
    venue: 'Parramatta Town Hall',
    address: '182 Church St, Parramatta NSW 2150',
    date: soon(7),
    time: '09:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1606298855672-3efb63017be8?w=800',
    imageColor: '#F59E0B',
    cultureTag: ['Tamil', 'South Indian'],
    tags: ['pongal', 'harvest', 'family', 'traditional'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 800,
    attending: 412,
    organizerId: 'seed-org-2',
    organizer: 'Tamil Sangam NSW',
    organizerReputationScore: 88,
    status: 'published',
    cpid: 'CP-E-PONGSYD',
    councilPartner: 'Parramatta City Council',
    tiers: [],
  },
  {
    title: 'Bollywood Night — Live DJ & Dance',
    description: "Sydney's hottest Bollywood party! Dance the night away with live DJ sets, costume competition, and authentic cocktails from the Indian subcontinent.",
    communityId: 'Bollywood',
    venue: 'The Star Event Centre',
    address: '80 Pyrmont St, Pyrmont NSW 2009',
    date: soon(21),
    time: '08:00 PM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?w=800',
    imageColor: '#7C3AED',
    cultureTag: ['Bollywood', 'South Asian', 'Hindi'],
    tags: ['party', 'dance', 'dj', 'nightlife'],
    category: 'Nightlife',
    priceTier: 'mid',
    priceCents: 3500,
    priceLabel: '$35',
    isFree: false,
    isFeatured: true,
    capacity: 600,
    attending: 521,
    organizerId: 'seed-org-3',
    organizer: 'Desi Nights Sydney',
    organizerReputationScore: 85,
    status: 'published',
    cpid: 'CP-E-BNISYD',
    tiers: [
      { name: 'Standard', priceCents: 3500, available: 400 },
      { name: 'VIP Table', priceCents: 15000, available: 20 },
    ],
  },
  {
    title: 'Chinese New Year — Dragon Dance Parade',
    description: 'Ring in the Year of the Snake with dragon and lion dances through Chinatown, a lantern festival and dumpling-making workshops. Presented by City of Sydney Council.',
    communityId: 'Chinese',
    venue: 'Sydney Chinatown',
    address: 'Dixon St, Haymarket NSW 2000',
    date: soon(10),
    time: '06:00 PM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800',
    imageColor: '#DC2626',
    cultureTag: ['Chinese', 'East Asian'],
    tags: ['new year', 'parade', 'lantern', 'family'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 5000,
    attending: 3211,
    organizerId: 'seed-org-5',
    organizer: 'Sydney Chinese Community Association',
    organizerReputationScore: 96,
    status: 'published',
    cpid: 'CP-E-CNYSYD',
    councilPartner: 'City of Sydney',
    tiers: [],
  },
  {
    title: 'Indigenous Storytelling Night — NAIDOC Week',
    description: 'An intimate evening of First Nations storytelling, traditional music, and art featuring local Gadigal artists. Proceeds support local Indigenous youth programs.',
    communityId: 'Aboriginal',
    venue: 'Carriageworks',
    address: '245 Wilson St, Eveleigh NSW 2015',
    date: soon(35),
    time: '07:30 PM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    imageColor: '#92400E',
    cultureTag: ['Aboriginal', 'First Nations', 'Indigenous'],
    indigenousTags: ['Gadigal', 'Naidoc'],
    tags: ['storytelling', 'art', 'naidoc', 'cultural'],
    category: 'Arts',
    priceTier: 'low',
    priceCents: 1500,
    priceLabel: '$15',
    isFree: false,
    isFeatured: true,
    capacity: 200,
    attending: 156,
    organizerId: 'seed-org-8',
    organizer: 'Gadigal Art Collective',
    organizerReputationScore: 94,
    status: 'published',
    cpid: 'CP-E-INDSYD',
    councilPartner: 'City of Sydney',
    tiers: [{ name: 'General', priceCents: 1500, available: 100 }],
  },
  {
    title: 'Nigerian Independence Day Gala',
    description: 'Celebrate Nigerian independence with Afrobeat live performances, jollof cook-off, fashion showcase, and traditional masquerade.',
    communityId: 'Nigerian',
    venue: 'Doltone House Hyde Park',
    address: '181 Elizabeth St, Sydney NSW 2000',
    date: soon(45),
    time: '07:00 PM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=800',
    imageColor: '#16A34A',
    cultureTag: ['Nigerian', 'African', 'Afrobeat'],
    tags: ['independence', 'gala', 'music', 'food'],
    category: 'Gala',
    priceTier: 'premium',
    priceCents: 8500,
    priceLabel: '$85',
    isFree: false,
    isFeatured: false,
    capacity: 300,
    attending: 187,
    organizerId: 'seed-org-6',
    organizer: 'Nigerian Community Australia',
    organizerReputationScore: 82,
    status: 'published',
    cpid: 'CP-E-NIGSYD',
    tiers: [
      { name: 'Standard', priceCents: 8500, available: 200 },
      { name: 'VIP', priceCents: 20000, available: 30 },
    ],
  },
  {
    title: 'Lebanese Food & Music Festival',
    description: 'A celebration of Lebanese culture in Lakemba — mezze spreads, live dabke dancing, oud music, and Arabic calligraphy workshops for all ages.',
    communityId: 'Lebanese',
    venue: 'Lakemba Park',
    address: 'Railway Pde, Lakemba NSW 2195',
    date: soon(28),
    time: '11:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    imageColor: '#B45309',
    cultureTag: ['Lebanese', 'Middle Eastern', 'Arab'],
    tags: ['food', 'music', 'dance', 'family'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 1500,
    attending: 892,
    organizerId: 'seed-org-11',
    organizer: 'Lebanese Australian Association',
    organizerReputationScore: 83,
    status: 'published',
    cpid: 'CP-E-LEBSYD',
    councilPartner: 'Canterbury-Bankstown Council',
    tiers: [],
  },
  {
    title: 'Multicultural Fair — Harmony Day',
    description: 'Canterbury-Bankstown Council presents the annual Harmony Day Fair. 40+ cultural stalls, live performances, food trucks from 20 cultures, and children\'s activities.',
    communityId: 'Multicultural',
    venue: 'Bankstown City Plaza',
    address: 'Paul Keating Park, Bankstown NSW 2200',
    date: soon(6),
    time: '10:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800',
    imageColor: '#0EA5E9',
    cultureTag: ['Multicultural'],
    tags: ['harmony day', 'multicultural', 'family', 'council'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 8000,
    attending: 4312,
    organizerId: 'seed-org-12',
    organizer: 'Canterbury-Bankstown Council',
    organizerReputationScore: 98,
    status: 'published',
    cpid: 'CP-E-HARMSYD',
    councilPartner: 'Canterbury-Bankstown Council',
    tiers: [],
  },
  {
    title: 'Sikh Vaisakhi Nagar Kirtan — Sydney',
    description: 'The annual Sikh harvest festival and procession through Parramatta, with free langar (community meal), kirtan performances, and cultural displays.',
    communityId: 'Sikh',
    venue: 'Parramatta CBD',
    address: 'Church St to Parramatta River, Parramatta NSW 2150',
    date: soon(16),
    time: '08:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800',
    imageColor: '#D97706',
    cultureTag: ['Sikh', 'Punjabi', 'South Asian'],
    tags: ['vaisakhi', 'procession', 'kirtan', 'family'],
    category: 'Religious',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 10000,
    attending: 7823,
    organizerId: 'seed-org-13',
    organizer: 'Sikh Council of Australia',
    organizerReputationScore: 97,
    status: 'published',
    cpid: 'CP-E-SIKSYD',
    councilPartner: 'Parramatta City Council',
    tiers: [],
  },

  // ── MELBOURNE ──────────────────────────────────────────────────────────────
  {
    title: 'Melbourne Diwali Lights Festival',
    description: "Melbourne lights up for Diwali at Federation Square. Spectacular light show, rangoli competition, and South Asian street food. City of Melbourne's biggest cultural event.",
    communityId: 'South Asian',
    venue: 'Federation Square',
    address: 'Corner of Flinders & Swanston St, Melbourne VIC 3000',
    date: soon(12),
    time: '07:00 PM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    imageColor: '#F97316',
    cultureTag: ['South Asian', 'Hindu', 'Diwali'],
    tags: ['diwali', 'lights', 'festival', 'outdoor'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 10000,
    attending: 7234,
    organizerId: 'seed-org-9',
    organizer: 'Festival of India Melbourne',
    organizerReputationScore: 97,
    status: 'published',
    cpid: 'CP-E-DIVMLB',
    councilPartner: 'City of Melbourne',
    tiers: [],
  },
  {
    title: 'Vietnamese Tet New Year Market — Springvale',
    description: "Celebrate Lunar New Year with the Vietnamese community. Traditional music, ao dai fashion show, bánh mì cook-off, and children's activities. Free entry.",
    communityId: 'Vietnamese',
    venue: 'Springvale Town Centre',
    address: 'Springvale Rd, Springvale VIC 3171',
    date: soon(8),
    time: '10:00 AM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    imageColor: '#FBBF24',
    cultureTag: ['Vietnamese', 'Southeast Asian'],
    tags: ['tet', 'new year', 'market', 'food'],
    category: 'Market',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 3000,
    attending: 1876,
    organizerId: 'seed-org-10',
    organizer: 'Vietnamese Community Australia',
    organizerReputationScore: 87,
    status: 'published',
    cpid: 'CP-E-TETMLB',
    councilPartner: 'Greater Dandenong Council',
    tiers: [],
  },
  {
    title: 'Greek Panigiri — Melbourne Antipodes Festival',
    description: "Melbourne's annual celebration of Hellenic culture. Three days of live Greek music, traditional dance workshops, authentic food, and film screenings.",
    communityId: 'Greek',
    venue: 'Lonsdale St Greek Precinct',
    address: 'Lonsdale St, Melbourne VIC 3000',
    date: soon(22),
    time: '12:00 PM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    imageColor: '#1D4ED8',
    cultureTag: ['Greek', 'Mediterranean', 'European'],
    tags: ['antipodes', 'greek', 'festival', 'multicultural'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 15000,
    attending: 9102,
    organizerId: 'seed-org-14',
    organizer: 'Hellenic Community of Victoria',
    organizerReputationScore: 95,
    status: 'published',
    cpid: 'CP-E-GREMLB',
    councilPartner: 'City of Melbourne',
    tiers: [],
  },
  {
    title: "Moomba Festival — First Nations Day",
    description: "City of Melbourne's Moomba Festival First Nations Day celebration on the Yarra River. Gunditjmara and Wurundjeri artists, cultural performances, and food.",
    communityId: 'Aboriginal',
    venue: 'Alexandra Gardens',
    address: 'Alexandra Ave, Melbourne VIC 3004',
    date: soon(40),
    time: '10:00 AM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    imageColor: '#78350F',
    cultureTag: ['Aboriginal', 'First Nations', 'Indigenous'],
    indigenousTags: ['Wurundjeri', 'Gunditjmara'],
    tags: ['moomba', 'first nations', 'yarra', 'council'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 20000,
    attending: 14500,
    organizerId: 'seed-org-15',
    organizer: 'City of Melbourne',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-MMBMLB',
    councilPartner: 'City of Melbourne',
    tiers: [],
  },

  // ── BRISBANE ───────────────────────────────────────────────────────────────
  {
    title: 'Brisbane Multicultural Month — Pacific Islander Showcase',
    description: "Brisbane City Council's annual Pacific showcase featuring Samoan, Tongan, and Fijian cultural performances, traditional food, and craft market.",
    communityId: 'Pacific Islander',
    venue: 'South Bank Parklands',
    address: 'Grey St, South Brisbane QLD 4101',
    date: soon(19),
    time: '10:00 AM',
    city: 'Brisbane',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800',
    imageColor: '#0891B2',
    cultureTag: ['Pacific Islander', 'Samoan', 'Fijian', 'Tongan'],
    tags: ['pacific', 'multicultural', 'council', 'family'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 5000,
    attending: 2876,
    organizerId: 'seed-org-16',
    organizer: 'Brisbane City Council',
    organizerReputationScore: 98,
    status: 'published',
    cpid: 'CP-E-PACBRB',
    councilPartner: 'Brisbane City Council',
    tiers: [],
  },
  {
    title: 'Korean Cultural Day — Gangnam Style Brisbane',
    description: "K-pop dance workshop, Korean street food, traditional hanbok dress-up, and taekwondo demonstrations at South Bank.",
    communityId: 'Korean',
    venue: 'South Bank Cultural Forecourt',
    address: 'Melbourne St, South Brisbane QLD 4101',
    date: soon(26),
    time: '11:00 AM',
    city: 'Brisbane',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?w=800',
    imageColor: '#7C3AED',
    cultureTag: ['Korean', 'East Asian'],
    tags: ['k-pop', 'korean', 'food', 'dance'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 2000,
    attending: 1234,
    organizerId: 'seed-org-17',
    organizer: 'Korean Community Brisbane',
    organizerReputationScore: 81,
    status: 'published',
    cpid: 'CP-E-KORBRB',
    tiers: [],
  },

  // ── AUCKLAND ───────────────────────────────────────────────────────────────
  {
    title: 'Pasifika Festival — Auckland Waterfront',
    description: "The Southern Hemisphere's largest Pacific Island festival on Auckland's waterfront. 16 Pacific nations, over 100 performers, and authentic island food.",
    communityId: 'Pacific Islander',
    venue: 'Western Springs Park',
    address: 'Great North Rd, Auckland 1010, New Zealand',
    date: soon(15),
    time: '10:00 AM',
    city: 'Auckland',
    country: 'New Zealand',
    imageUrl: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=800',
    imageColor: '#0369A1',
    cultureTag: ['Samoan', 'Tongan', 'Fijian', 'Cook Islands', 'Niuean', 'Pacific Islander'],
    tags: ['pasifika', 'pacific', 'festival', 'waterfront'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 30000,
    attending: 22000,
    organizerId: 'seed-org-18',
    organizer: 'Auckland Council',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-PASAKL',
    councilPartner: 'Auckland Council',
    tiers: [],
  },
  {
    title: 'Māori New Year — Matariki Lantern Walk',
    description: "Celebrate Matariki (Māori New Year) with a guided lantern walk through Auckland Domain, storytelling by Ngāti Whātua elders, and traditional kai (food).",
    communityId: 'Māori',
    venue: 'Auckland Domain',
    address: 'Park Rd, Grafton, Auckland 1023, New Zealand',
    date: soon(33),
    time: '07:00 PM',
    city: 'Auckland',
    country: 'New Zealand',
    imageUrl: 'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=800',
    imageColor: '#4F46E5',
    cultureTag: ['Māori', 'Indigenous', 'First Nations'],
    indigenousTags: ['Ngāti Whātua', 'Matariki'],
    tags: ['matariki', 'maori', 'lanterns', 'new year'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 5000,
    attending: 3201,
    organizerId: 'seed-org-19',
    organizer: 'Auckland Council',
    organizerReputationScore: 97,
    status: 'published',
    cpid: 'CP-E-MATAKL',
    councilPartner: 'Auckland Council',
    tiers: [],
  },

  // ── DUBAI ──────────────────────────────────────────────────────────────────
  {
    title: 'Eid Al Fitr Festival — Dubai Global Village',
    description: 'Celebrate the end of Ramadan at Dubai Global Village with traditional Emirati sweets, henna artists, traditional dance, and live nasheeds.',
    communityId: 'Arab',
    venue: 'Dubai Global Village',
    address: 'Sheikh Mohammed Bin Zayed Rd, Dubai, UAE',
    date: soon(11),
    time: '06:00 PM',
    city: 'Dubai',
    country: 'UAE',
    imageUrl: 'https://images.unsplash.com/photo-1542396601-dca920ea2807?w=800',
    imageColor: '#B45309',
    cultureTag: ['Arab', 'Emirati', 'Muslim'],
    tags: ['eid', 'ramadan', 'festival', 'family'],
    category: 'Festival',
    priceTier: 'low',
    priceCents: 1500,
    priceLabel: 'AED 15',
    isFree: false,
    isFeatured: true,
    capacity: 50000,
    attending: 38421,
    organizerId: 'seed-org-20',
    organizer: 'Dubai Events Authority',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-EIDDXB',
    tiers: [{ name: 'General', priceCents: 1500, available: 40000 }],
  },
  {
    title: 'Indian Holi Festival — Dubai',
    description: "Dubai's largest Holi celebration at Dubai Media City Amphitheatre. Colour powder, live Bollywood music, and traditional sweets. All nationalities welcome.",
    communityId: 'South Asian',
    venue: 'Dubai Media City Amphitheatre',
    address: 'Media City, Dubai, UAE',
    date: soon(9),
    time: '04:00 PM',
    city: 'Dubai',
    country: 'UAE',
    imageUrl: 'https://images.unsplash.com/photo-1555679486-e341b9bb7d7e?w=800',
    imageColor: '#EC4899',
    cultureTag: ['South Asian', 'Hindu', 'Holi'],
    tags: ['holi', 'colours', 'festival', 'bollywood'],
    category: 'Festival',
    priceTier: 'mid',
    priceCents: 4000,
    priceLabel: 'AED 40',
    isFree: false,
    isFeatured: true,
    capacity: 8000,
    attending: 5632,
    organizerId: 'seed-org-21',
    organizer: 'Holi Hai Dubai',
    organizerReputationScore: 89,
    status: 'published',
    cpid: 'CP-E-HOLIDXB',
    tiers: [
      { name: 'Standard', priceCents: 4000, available: 6000 },
      { name: 'VIP (early entry + gift kit)', priceCents: 12000, available: 500 },
    ],
  },

  // ── LONDON ─────────────────────────────────────────────────────────────────
  {
    title: 'Notting Hill Carnival — Community Pre-Party',
    description: "The official community warm-up for Notting Hill Carnival, featuring steel drum workshops, Caribbean food, mas costume making, and soca DJ sets.",
    communityId: 'Caribbean',
    venue: 'Ladbroke Grove Community Hall',
    address: 'Ladbroke Grove, London W10 5AA, UK',
    date: soon(18),
    time: '02:00 PM',
    city: 'London',
    country: 'United Kingdom',
    imageUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800',
    imageColor: '#7C3AED',
    cultureTag: ['Caribbean', 'Trinidadian', 'Jamaican'],
    tags: ['carnival', 'steel drum', 'soca', 'caribbean'],
    category: 'Festival',
    priceTier: 'low',
    priceCents: 1500,
    priceLabel: '£15',
    isFree: false,
    isFeatured: true,
    capacity: 500,
    attending: 387,
    organizerId: 'seed-org-22',
    organizer: 'Notting Hill Carnival Trust',
    organizerReputationScore: 96,
    status: 'published',
    cpid: 'CP-E-NHLLON',
    tiers: [{ name: 'General', priceCents: 1500, available: 400 }],
  },
  {
    title: 'Diwali in Trafalgar Square',
    description: 'London Mayor\'s Diwali event at Trafalgar Square. Bollywood dance performances, Indian street food, fireworks, and a spectacular light display.',
    communityId: 'South Asian',
    venue: 'Trafalgar Square',
    address: 'Trafalgar Square, London WC2N 5DN, UK',
    date: soon(13),
    time: '05:00 PM',
    city: 'London',
    country: 'United Kingdom',
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    imageColor: '#F97316',
    cultureTag: ['South Asian', 'Hindu', 'Diwali'],
    tags: ['diwali', 'trafalgar', 'london', 'outdoor'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 25000,
    attending: 19870,
    organizerId: 'seed-org-23',
    organizer: "Mayor's Office London",
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-DIVLON',
    councilPartner: 'Greater London Authority',
    tiers: [],
  },

  // ── TORONTO ────────────────────────────────────────────────────────────────
  {
    title: 'Caribana — Toronto Caribbean Carnival',
    description: "North America's largest Caribbean festival. The King and Queen mas costume parade, steel band competition, and Caribbean Panorama at Exhibition Place.",
    communityId: 'Caribbean',
    venue: 'Exhibition Place',
    address: '100 Princes Blvd, Toronto, ON M6K 3C3, Canada',
    date: soon(25),
    time: '10:00 AM',
    city: 'Toronto',
    country: 'Canada',
    imageUrl: 'https://images.unsplash.com/photo-1499364615650-ec38552f4f34?w=800',
    imageColor: '#DC2626',
    cultureTag: ['Caribbean', 'Trinidadian', 'Jamaican', 'Barbadian'],
    tags: ['caribana', 'carnival', 'parade', 'toronto'],
    category: 'Festival',
    priceTier: 'mid',
    priceCents: 3000,
    priceLabel: 'CAD $30',
    isFree: false,
    isFeatured: true,
    capacity: 100000,
    attending: 87000,
    organizerId: 'seed-org-24',
    organizer: 'Toronto Caribbean Carnival',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-CAKTOR',
    councilPartner: 'City of Toronto',
    tiers: [
      { name: 'General', priceCents: 3000, available: 80000 },
      { name: 'Grandstand VIP', priceCents: 8000, available: 5000 },
    ],
  },
  {
    title: 'Taste of the Danforth — Greek Festival',
    description: "Toronto's beloved Greektown festival, celebrating Hellenic culture with souvlaki, live music, traditional dances, and the iconic taste of the Mediterranean.",
    communityId: 'Greek',
    venue: 'Danforth Ave',
    address: 'Danforth Ave, Toronto, ON M4K, Canada',
    date: soon(38),
    time: '11:00 AM',
    city: 'Toronto',
    country: 'Canada',
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
    imageColor: '#1D4ED8',
    cultureTag: ['Greek', 'Mediterranean'],
    tags: ['greek', 'danforth', 'festival', 'food'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 50000,
    attending: 41000,
    organizerId: 'seed-org-25',
    organizer: 'Greek Community of Toronto',
    organizerReputationScore: 93,
    status: 'published',
    cpid: 'CP-E-GRETOR',
    councilPartner: 'City of Toronto',
    tiers: [],
  },

  // ── VANCOUVER ──────────────────────────────────────────────────────────────
  {
    title: 'Vancouver Lunar New Year Parade',
    description: 'Chinatown Lunar New Year parade with traditional lion dances, firecrackers, and a night market with food from across East and Southeast Asia.',
    communityId: 'Chinese',
    venue: 'Vancouver Chinatown',
    address: 'E Pender St, Vancouver, BC, Canada',
    date: soon(5),
    time: '11:00 AM',
    city: 'Vancouver',
    country: 'Canada',
    imageUrl: 'https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?w=800',
    imageColor: '#DC2626',
    cultureTag: ['Chinese', 'East Asian', 'Vietnamese'],
    tags: ['lunar new year', 'parade', 'chinatown', 'family'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 20000,
    attending: 15600,
    organizerId: 'seed-org-26',
    organizer: 'Vancouver Chinatown BIA',
    organizerReputationScore: 94,
    status: 'published',
    cpid: 'CP-E-LNRVAN',
    councilPartner: 'City of Vancouver',
    tiers: [],
  },

  // ── ADELAIDE ───────────────────────────────────────────────────────────────
  {
    title: 'Adelaide Fringe — Multicultural Night Market',
    description: 'Adelaide Fringe special edition multicultural night market at Adelaide Central Market. Street food from 25+ cultures, live music, and family performances.',
    communityId: 'Multicultural',
    venue: 'Adelaide Central Market',
    address: '44-60 Gouger St, Adelaide SA 5000',
    date: soon(20),
    time: '05:00 PM',
    city: 'Adelaide',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800',
    imageColor: '#D97706',
    cultureTag: ['Multicultural'],
    tags: ['fringe', 'night market', 'food', 'multicultural'],
    category: 'Market',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 4000,
    attending: 2341,
    organizerId: 'seed-org-27',
    organizer: 'Adelaide Fringe Inc.',
    organizerReputationScore: 96,
    status: 'published',
    cpid: 'CP-E-FRGADL',
    councilPartner: 'City of Adelaide',
    tiers: [],
  },
  {
    title: 'Kaurna Cultural Walk — Tandanya',
    description: 'A guided cultural walk through Adelaide with Kaurna Elders, exploring traditional stories of the Adelaide Plains. Hosted in partnership with Tandanya National Aboriginal Cultural Institute.',
    communityId: 'Aboriginal',
    venue: 'Tandanya Cultural Institute',
    address: '253 Grenfell St, Adelaide SA 5000',
    date: soon(30),
    time: '09:30 AM',
    city: 'Adelaide',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    imageColor: '#92400E',
    cultureTag: ['Aboriginal', 'First Nations', 'Indigenous'],
    indigenousTags: ['Kaurna'],
    tags: ['cultural walk', 'indigenous', 'storytelling', 'heritage'],
    category: 'Cultural',
    priceTier: 'low',
    priceCents: 2000,
    priceLabel: '$20',
    isFree: false,
    isFeatured: false,
    capacity: 30,
    attending: 22,
    organizerId: 'seed-org-28',
    organizer: 'Tandanya National Aboriginal Cultural Institute',
    organizerReputationScore: 97,
    status: 'published',
    cpid: 'CP-E-KAUADL',
    councilPartner: 'City of Adelaide',
    tiers: [{ name: 'General', priceCents: 2000, available: 30 }],
  },
  {
    title: 'WOMADelaide — World Music & Dance',
    description: "Adelaide's beloved world music festival returns to Botanic Park. Artists from 30+ countries performing across 6 stages, with immersive cultural experiences.",
    communityId: 'World Music',
    venue: 'Botanic Park',
    address: 'Plane Tree Dr, Adelaide SA 5000',
    date: soon(42),
    time: '12:00 PM',
    city: 'Adelaide',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?w=800',
    imageColor: '#7C3AED',
    cultureTag: ['World Music', 'Multicultural'],
    tags: ['womad', 'world music', 'dance', 'festival'],
    category: 'Music',
    priceTier: 'premium',
    priceCents: 8500,
    priceLabel: '$85',
    isFree: false,
    isFeatured: true,
    capacity: 25000,
    attending: 19800,
    organizerId: 'seed-org-29',
    organizer: 'WOMAD Adelaide',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-WOMADL',
    councilPartner: 'City of Adelaide',
    tiers: [
      { name: 'Day Pass', priceCents: 8500, available: 20000 },
      { name: '3-Day Pass', priceCents: 22000, available: 5000 },
    ],
  },

  // ── PERTH ──────────────────────────────────────────────────────────────────
  {
    title: 'Perth Diwali Festival — Kings Park',
    description: "Perth's largest Diwali celebration at Kings Park and Botanic Garden. Light installations, Bollywood performances, and street food along Fraser Ave.",
    communityId: 'South Asian',
    venue: 'Kings Park and Botanic Garden',
    address: 'Fraser Ave, West Perth WA 6005',
    date: soon(13),
    time: '06:30 PM',
    city: 'Perth',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    imageColor: '#F97316',
    cultureTag: ['South Asian', 'Hindu', 'Diwali'],
    tags: ['diwali', 'festival', 'lights', 'perth'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 12000,
    attending: 8750,
    organizerId: 'seed-org-30',
    organizer: 'Hindu Council of Western Australia',
    organizerReputationScore: 91,
    status: 'published',
    cpid: 'CP-E-DIVPER',
    councilPartner: 'City of Perth',
    tiers: [],
  },
  {
    title: 'Perth Harmony Week — Multicultural Showcase',
    description: 'City of Perth celebrates Harmony Week with multicultural performances, workshops, and a lantern parade through the CBD. Highlights the 170+ nationalities living in Perth.',
    communityId: 'Multicultural',
    venue: 'Forrest Place',
    address: 'Forrest Pl, Perth WA 6000',
    date: soon(6),
    time: '11:00 AM',
    city: 'Perth',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800',
    imageColor: '#0EA5E9',
    cultureTag: ['Multicultural'],
    tags: ['harmony week', 'multicultural', 'perth', 'council'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 6000,
    attending: 3980,
    organizerId: 'seed-org-31',
    organizer: 'City of Perth',
    organizerReputationScore: 98,
    status: 'published',
    cpid: 'CP-E-HARPER',
    councilPartner: 'City of Perth',
    tiers: [],
  },
  {
    title: 'Noongar Boodja Dreaming Walk',
    description: "A Whadjuk Noongar Elder-led cultural walk through Perth's foreshore, sharing Dreaming stories of Derbarl Yerrigan (the Swan River). Includes traditional fire-making demonstration.",
    communityId: 'Aboriginal',
    venue: 'Elizabeth Quay',
    address: 'The Esplanade, Perth WA 6000',
    date: soon(24),
    time: '08:00 AM',
    city: 'Perth',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    imageColor: '#78350F',
    cultureTag: ['Aboriginal', 'First Nations', 'Indigenous'],
    indigenousTags: ['Whadjuk Noongar'],
    tags: ['dreaming', 'cultural walk', 'noongar', 'indigenous'],
    category: 'Cultural',
    priceTier: 'low',
    priceCents: 2500,
    priceLabel: '$25',
    isFree: false,
    isFeatured: false,
    capacity: 20,
    attending: 16,
    organizerId: 'seed-org-32',
    organizer: 'Noongar Cultural Experiences',
    organizerReputationScore: 95,
    status: 'published',
    cpid: 'CP-E-NOOBRP',
    tiers: [{ name: 'General', priceCents: 2500, available: 20 }],
  },

  // ── CANBERRA ───────────────────────────────────────────────────────────────
  {
    title: 'Multicultural Festival — National Multicultural Festival Canberra',
    description: 'The ACT Government presents Canberra\'s iconic multicultural festival across the city centre. 70+ food stalls, 100+ performances from 60+ nationalities.',
    communityId: 'Multicultural',
    venue: 'Civic Square & Garema Place',
    address: 'Civic Square, Canberra ACT 2601',
    date: soon(17),
    time: '10:00 AM',
    city: 'Canberra',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800',
    imageColor: '#059669',
    cultureTag: ['Multicultural'],
    tags: ['multicultural', 'festival', 'canberra', 'act'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 50000,
    attending: 38600,
    organizerId: 'seed-org-33',
    organizer: 'ACT Government — Multicultural Affairs',
    organizerReputationScore: 99,
    status: 'published',
    cpid: 'CP-E-MULCBR',
    councilPartner: 'ACT Government',
    tiers: [],
  },
  {
    title: 'NAIDOC Week — Ngunnawal Country Walk',
    description: 'Walk the land with Ngunnawal Elders around Lake Burley Griffin. Share in the stories of the Ngunnawal people whose country Canberra sits on.',
    communityId: 'Aboriginal',
    venue: 'National Museum of Australia',
    address: 'Lawson Cres, Acton Peninsula ACT 2601',
    date: soon(35),
    time: '09:00 AM',
    city: 'Canberra',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    imageColor: '#92400E',
    cultureTag: ['Aboriginal', 'First Nations', 'Indigenous'],
    indigenousTags: ['Ngunnawal'],
    tags: ['naidoc', 'ngunnawal', 'cultural walk', 'canberra'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 100,
    attending: 78,
    organizerId: 'seed-org-34',
    organizer: 'National Museum of Australia',
    organizerReputationScore: 98,
    status: 'published',
    cpid: 'CP-E-NGUCBR',
    councilPartner: 'ACT Government',
    tiers: [],
  },

  // ── ADDITIONAL SYDNEY EVENTS ────────────────────────────────────────────────
  {
    title: 'Persian New Year — Nowruz Sydney',
    description: 'Ring in the Persian New Year at Hyde Park. Haft-sin table displays, live classical Persian music, poetry readings, and traditional Iranian food market.',
    communityId: 'Persian',
    venue: 'Hyde Park South',
    address: 'Elizabeth St & College St, Sydney NSW 2000',
    date: soon(8),
    time: '02:00 PM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1563897539633-7374c6e7e8af?w=800',
    imageColor: '#10B981',
    cultureTag: ['Persian', 'Iranian', 'Middle Eastern'],
    tags: ['nowruz', 'persian new year', 'iran', 'culture'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 1200,
    attending: 745,
    organizerId: 'seed-org-35',
    organizer: 'Iranian Community Sydney',
    organizerReputationScore: 84,
    status: 'published',
    cpid: 'CP-E-NRZSYD',
    tiers: [],
  },
  {
    title: 'Filipino Fiesta de Santos — Sydney',
    description: 'A vibrant celebration of Filipino culture featuring the Sinulog procession, lechon roast, Tinikling folk dance, and live OPM music. Organised with City of Sydney.',
    communityId: 'Filipino',
    venue: 'Auburn Botanic Gardens',
    address: 'Chiswick Rd, Auburn NSW 2144',
    date: soon(31),
    time: '10:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=800',
    imageColor: '#F59E0B',
    cultureTag: ['Filipino', 'Southeast Asian'],
    tags: ['fiesta', 'filipino', 'dance', 'food'],
    category: 'Cultural',
    priceTier: 'low',
    priceCents: 1000,
    priceLabel: '$10',
    isFree: false,
    isFeatured: false,
    capacity: 2000,
    attending: 1430,
    organizerId: 'seed-org-36',
    organizer: 'Filipino-Australian Community Foundation',
    organizerReputationScore: 86,
    status: 'published',
    cpid: 'CP-E-FILSYD',
    councilPartner: 'Cumberland City Council',
    tiers: [{ name: 'General', priceCents: 1000, available: 1500 }],
  },
  {
    title: 'Japanese Sakura Festival — Dangar Island',
    description: "Celebrate the cherry blossom season at Sydney's Japanese gardens. Traditional tea ceremony, ikebana demonstrations, taiko drumming, and cherry blossom viewing walks.",
    communityId: 'Japanese',
    venue: 'Auburn Japanese Gardens',
    address: 'Chiswick Rd, Auburn NSW 2144',
    date: soon(18),
    time: '10:00 AM',
    city: 'Sydney',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1522383225653-ed111181a951?w=800',
    imageColor: '#EC4899',
    cultureTag: ['Japanese', 'East Asian'],
    tags: ['sakura', 'cherry blossom', 'japanese', 'tea ceremony'],
    category: 'Cultural',
    priceTier: 'low',
    priceCents: 1500,
    priceLabel: '$15',
    isFree: false,
    isFeatured: true,
    capacity: 500,
    attending: 423,
    organizerId: 'seed-org-37',
    organizer: 'Japan Australia Association NSW',
    organizerReputationScore: 89,
    status: 'published',
    cpid: 'CP-E-SAKSYD',
    tiers: [{ name: 'General', priceCents: 1500, available: 400 }],
  },

  // ── ADDITIONAL MELBOURNE EVENTS ─────────────────────────────────────────────
  {
    title: 'Melbourne Ramadan Night Market',
    description: 'Celebrate Ramadan with Melbourne\'s Muslim community at the Queen Vic Night Market special edition. Halal food from 30+ vendors, henna artists, and nasheeds after Iftar.',
    communityId: 'Muslim',
    venue: 'Queen Victoria Market',
    address: 'Queen St, Melbourne VIC 3000',
    date: soon(4),
    time: '07:00 PM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800',
    imageColor: '#065F46',
    cultureTag: ['Muslim', 'Middle Eastern', 'South Asian', 'African'],
    tags: ['ramadan', 'night market', 'halal', 'iftar'],
    category: 'Market',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 8000,
    attending: 6200,
    organizerId: 'seed-org-38',
    organizer: 'Islamic Council of Victoria',
    organizerReputationScore: 93,
    status: 'published',
    cpid: 'CP-E-RAMMLB',
    councilPartner: 'City of Melbourne',
    tiers: [],
  },
  {
    title: 'Sri Lankan Independence Day — Melbourne',
    description: 'A colourful celebration of Sri Lankan Independence Day at Dandenong featuring classical Kandyan dance, drumming, Sri Lankan food, and cultural exhibits.',
    communityId: 'Sri Lankan',
    venue: 'Dandenong Civic Centre',
    address: 'Langhorne St, Dandenong VIC 3175',
    date: soon(23),
    time: '11:00 AM',
    city: 'Melbourne',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    imageColor: '#B45309',
    cultureTag: ['Sri Lankan', 'South Asian'],
    tags: ['independence day', 'sri lanka', 'dance', 'food'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 1500,
    attending: 980,
    organizerId: 'seed-org-39',
    organizer: 'Sri Lanka Australia Association Victoria',
    organizerReputationScore: 83,
    status: 'published',
    cpid: 'CP-E-SLKMLB',
    councilPartner: 'Greater Dandenong Council',
    tiers: [],
  },

  // ── ADDITIONAL AUCKLAND ─────────────────────────────────────────────────────
  {
    title: 'Auckland Diwali Festival',
    description: "Auckland's largest Indian cultural festival at Aotea Square. Spectacular Bollywood dance, regional Indian food, market stalls, and live entertainment across two stages.",
    communityId: 'South Asian',
    venue: 'Aotea Square',
    address: 'Aotea Square, Auckland 1010, New Zealand',
    date: soon(14),
    time: '12:00 PM',
    city: 'Auckland',
    country: 'New Zealand',
    imageUrl: 'https://images.unsplash.com/photo-1467810563316-b5476525c0f9?w=800',
    imageColor: '#F97316',
    cultureTag: ['South Asian', 'Hindu', 'Diwali'],
    tags: ['diwali', 'auckland', 'bollywood', 'festival'],
    category: 'Festival',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: true,
    capacity: 40000,
    attending: 31000,
    organizerId: 'seed-org-40',
    organizer: 'India New Zealand Business Council',
    organizerReputationScore: 95,
    status: 'published',
    cpid: 'CP-E-DIVAKL',
    councilPartner: 'Auckland Council',
    tiers: [],
  },

  // ── ADDITIONAL BRISBANE ────────────────────────────────────────────────────
  {
    title: 'Sri Lankan Independence Day — Brisbane',
    description: 'A colourful celebration of Sri Lankan Independence with Kandyan dance, drumming, Sri Lankan food, and cultural exhibits at Inala Civic Centre. All welcome.',
    communityId: 'Sri Lankan',
    venue: 'Inala Civic Centre',
    address: 'Corsair Ave, Inala QLD 4077',
    date: soon(36),
    time: '11:00 AM',
    city: 'Brisbane',
    country: 'Australia',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    imageColor: '#B45309',
    cultureTag: ['Sri Lankan', 'South Asian'],
    tags: ['independence day', 'sri lanka', 'dance', 'food'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 800,
    attending: 512,
    organizerId: 'seed-org-42',
    organizer: 'Sri Lanka Australia Association QLD',
    organizerReputationScore: 80,
    status: 'published',
    cpid: 'CP-E-SLKBRB',
    councilPartner: 'Brisbane City Council',
    tiers: [],
  },

  // ── ADDITIONAL DUBAI ───────────────────────────────────────────────────────
  {
    title: 'Eid Al Adha Celebration — Dubai',
    description: 'A family gathering at Dubai Cultural Village celebrating Eid Al Adha with traditional Emirati food, folk music, camel rides, and children\'s activities.',
    communityId: 'Arab',
    venue: 'Dubai Cultural Village (Al Shindagha)',
    address: 'Al Shindagha Rd, Bur Dubai, UAE',
    date: soon(29),
    time: '04:00 PM',
    city: 'Dubai',
    country: 'UAE',
    imageUrl: 'https://images.unsplash.com/photo-1542396601-dca920ea2807?w=800',
    imageColor: '#D97706',
    cultureTag: ['Arab', 'Emirati', 'Muslim'],
    tags: ['eid', 'family', 'emirati', 'cultural'],
    category: 'Cultural',
    priceTier: 'free',
    priceCents: 0,
    priceLabel: 'Free',
    isFree: true,
    isFeatured: false,
    capacity: 15000,
    attending: 11200,
    organizerId: 'seed-org-41',
    organizer: 'Dubai Culture & Arts Authority',
    organizerReputationScore: 97,
    status: 'published',
    cpid: 'CP-E-EIDADXB',
    tiers: [],
  },
] as const;

// ---------------------------------------------------------------------------
// Traditional Lands — used on home screen and in indigenous content
// ---------------------------------------------------------------------------

const TRADITIONAL_LANDS = [
  {
    id: 'tl-gadigal',
    city: 'Sydney',
    country: 'Australia',
    landName: 'Gadigal Land',
    traditionalCustodians: 'Gadigal People of the Eora Nation',
    acknowledgement: 'CulturePass acknowledges the Gadigal people of the Eora Nation as the traditional custodians of this land, and pays respect to Elders past, present, and emerging.',
    language: 'Dharug',
  },
  {
    id: 'tl-wurundjeri',
    city: 'Melbourne',
    country: 'Australia',
    landName: 'Wurundjeri Country',
    traditionalCustodians: 'Wurundjeri People of the Kulin Nation',
    acknowledgement: 'We acknowledge the Wurundjeri people of the Kulin Nation as the traditional custodians of the land on which Melbourne stands.',
    language: 'Woi wurrung',
  },
  {
    id: 'tl-turrbal',
    city: 'Brisbane',
    country: 'Australia',
    landName: 'Turrbal and Yugara Country',
    traditionalCustodians: 'Turrbal and Yugara People',
    acknowledgement: 'We acknowledge the Turrbal and Yugara peoples as the traditional custodians of Brisbane, and pay our respects to Elders past and present.',
    language: 'Yugarapul',
  },
  {
    id: 'tl-kaurna',
    city: 'Adelaide',
    country: 'Australia',
    landName: 'Kaurna Country',
    traditionalCustodians: 'Kaurna People',
    acknowledgement: 'CulturePass acknowledges the Kaurna people as the traditional custodians of the Adelaide Plains.',
    language: 'Kaurna',
  },
  {
    id: 'tl-ngunnawal',
    city: 'Canberra',
    country: 'Australia',
    landName: 'Ngunnawal Country',
    traditionalCustodians: 'Ngunnawal People',
    acknowledgement: 'We acknowledge the Ngunnawal people as the traditional custodians of the land on which Canberra stands.',
    language: 'Ngunnawal',
  },
  {
    id: 'tl-whadjuk',
    city: 'Perth',
    country: 'Australia',
    landName: 'Whadjuk Noongar Country',
    traditionalCustodians: 'Whadjuk People of the Noongar Nation',
    acknowledgement: 'We acknowledge the Whadjuk people of the Noongar Nation as the traditional custodians of the land on which Perth stands.',
    language: 'Noongar',
  },
  {
    id: 'tl-ngati-whatua',
    city: 'Auckland',
    country: 'New Zealand',
    landName: "Ngāti Whātua Ōrākei Ancestral Land",
    traditionalCustodians: "Ngāti Whātua Ōrākei",
    acknowledgement: "We acknowledge Ngāti Whātua Ōrākei as the tangata whenua (people of the land) of Auckland, Tāmaki Makaurau.",
    language: "Te Reo Māori",
  },
  {
    id: 'tl-muwinina',
    city: 'Hobart',
    country: 'Australia',
    landName: 'Muwinina Country',
    traditionalCustodians: 'Muwinina People of the Palawa Nation',
    acknowledgement: 'We acknowledge the Muwinina people as the traditional custodians of the land on which Hobart stands, and pay our respects to Elders past, present, and emerging.',
    language: 'Palawa kani',
  },
  {
    id: 'tl-larrakia',
    city: 'Darwin',
    country: 'Australia',
    landName: 'Larrakia Country',
    traditionalCustodians: 'Larrakia People',
    acknowledgement: 'We acknowledge the Larrakia people as the traditional custodians of Darwin. We pay our respects to their Elders and recognise their continuing connection to land, sea, and community.',
    language: 'Larrakia',
  },
  {
    id: 'tl-bidjigal',
    city: 'Parramatta',
    country: 'Australia',
    landName: 'Bidjigal and Burramattagal Country',
    traditionalCustodians: 'Bidjigal and Burramattagal Peoples of the Dharug Nation',
    acknowledgement: 'We acknowledge the Bidjigal and Burramattagal peoples as the traditional custodians of the Parramatta region. Parramatta takes its name from the Dharug word "Barramatta" meaning "the place where the eels lie down".',
    language: 'Dharug',
  },
  {
    id: 'tl-ngai-tahu',
    city: 'Christchurch',
    country: 'New Zealand',
    landName: 'Ngāi Tahu Rohe',
    traditionalCustodians: 'Ngāi Tahu',
    acknowledgement: "We acknowledge Ngāi Tahu as the tangata whenua of the South Island (Te Waipounamu). Christchurch, known as Ōtautahi, is named after the Ngāi Tahu rangatira Tautahi.",
    language: 'Te Reo Māori',
  },
  {
    id: 'tl-emirati',
    city: 'Dubai',
    country: 'UAE',
    landName: 'Bani Yas Tribal Territory',
    traditionalCustodians: 'Bani Yas Tribal Confederacy',
    acknowledgement: "CulturePass acknowledges the Bani Yas tribal confederacy as the founding people of the UAE, whose heritage and culture shaped the nation that became the United Arab Emirates. We recognise the deep cultural continuity of Emirati people across this land.",
    language: 'Arabic (Gulf dialect)',
  },
] as const;

// ---------------------------------------------------------------------------
// Indigenous Spotlights — First Nations content featured on home screen
// ---------------------------------------------------------------------------

const INDIGENOUS_SPOTLIGHTS = [
  {
    id: 'spot-1',
    title: 'Songlines: Tracking the Seven Sisters',
    description: 'A landmark exhibition by the National Museum of Australia celebrating the Martu Seven Sisters Dreaming — one of the most significant First Nations stories in the world.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    type: 'exhibition',
    city: 'Canberra',
    country: 'Australia',
    culturalGroup: 'Martu',
    websiteUrl: 'https://nma.gov.au',
  },
  {
    id: 'spot-2',
    title: 'Bangarra Dance Theatre — BASIC',
    description: 'Award-winning First Nations dance company Bangarra returns with their new production exploring identity, belonging, and First Nations cultural continuity.',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=800',
    type: 'performance',
    city: 'Sydney',
    country: 'Australia',
    culturalGroup: 'Various First Nations',
    websiteUrl: 'https://bangarra.com.au',
  },
  {
    id: 'spot-3',
    title: 'NAIDOC Week — Our Community, Our Future',
    description: "NAIDOC Week 2026 theme celebrates First Nations people's sustained efforts to care for Country and community. Events across every major Australian city.",
    imageUrl: 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
    type: 'event',
    city: 'National',
    country: 'Australia',
    culturalGroup: 'All First Nations',
    websiteUrl: 'https://naidoc.org.au',
  },
  {
    id: 'spot-4',
    title: 'Matariki — Māori New Year Exhibition',
    description: "Te Papa Tongarewa's annual Matariki exhibition celebrating the Māori New Year and the rising of the Pleiades star cluster. Free entry.",
    imageUrl: 'https://images.unsplash.com/photo-1494500764479-0c8f2919a3d8?w=800',
    type: 'exhibition',
    city: 'Auckland',
    country: 'New Zealand',
    culturalGroup: 'Māori',
    websiteUrl: 'https://tepapa.govt.nz',
  },
  {
    id: 'spot-5',
    title: 'Kaurna Warra — Adelaide Language Revival',
    description: 'The Kaurna Language revival project documents and teaches the endangered language of the Kaurna people of the Adelaide Plains through community classes and a digital archive.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    type: 'program',
    city: 'Adelaide',
    country: 'Australia',
    culturalGroup: 'Kaurna',
    websiteUrl: 'https://kaurna.com.au',
  },
  {
    id: 'spot-6',
    title: 'Bunjilaka Aboriginal Cultural Centre',
    description: "Melbourne Museum's Bunjilaka Centre — Victoria's premier destination for First Nations history, science, and cultural expression, featuring the Milarri Garden and permanent Kulin Nation exhibitions.",
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    type: 'institution',
    city: 'Melbourne',
    country: 'Australia',
    culturalGroup: 'Kulin Nations',
    websiteUrl: 'https://museumsvictoria.com.au/bunjilaka',
  },
  {
    id: 'spot-7',
    title: 'Larrakia Nation — Darwin Cultural Walks',
    description: 'Year-round guided cultural walks led by Larrakia Rangers sharing the ancient stories, bush tucker, and heritage of the sea-country people of Darwin and the Top End.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=800',
    type: 'experience',
    city: 'Darwin',
    country: 'Australia',
    culturalGroup: 'Larrakia',
    websiteUrl: 'https://larrakia.com',
  },
] as const;

// ---------------------------------------------------------------------------
// Profiles — Communities, Businesses, Venues, Artists
// Includes sponsorship flags for the business directory
// ---------------------------------------------------------------------------

const PROFILES = [
  // ── Communities
  {
    name: 'Kerala Community Sydney',
    entityType: 'community',
    description: 'The largest Malayalam-speaking community organisation in New South Wales, connecting over 15,000 members across Greater Sydney.',
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400',
    city: 'Sydney',
    country: 'Australia',
    website: 'https://keralasydney.org.au',
    rating: 4.8,
    membersCount: 15240,
    ownerId: 'seed-org-1',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Tamil Sangam NSW',
    entityType: 'community',
    description: 'Preserving and promoting Tamil culture, language, and heritage across New South Wales since 1972.',
    imageUrl: 'https://images.unsplash.com/photo-1577219491135-ce391730fb2c?w=400',
    city: 'Sydney',
    country: 'Australia',
    website: 'https://tamilsangamnsw.org.au',
    rating: 4.7,
    membersCount: 8900,
    ownerId: 'seed-org-2',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Vietnamese Community Australia',
    entityType: 'community',
    description: 'Supporting Vietnamese Australians in preserving culture, language, and community connection.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    city: 'Melbourne',
    country: 'Australia',
    rating: 4.6,
    membersCount: 22000,
    ownerId: 'seed-org-10',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Filipino-Australian Community Foundation',
    entityType: 'community',
    description: 'Championing the welfare, culture, and rights of Filipino Australians since 1989.',
    imageUrl: 'https://images.unsplash.com/photo-1527529482837-4698179dc6ce?w=400',
    city: 'Sydney',
    country: 'Australia',
    rating: 4.5,
    membersCount: 11200,
    ownerId: 'seed-org-4',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Sikh Council of Australia',
    entityType: 'community',
    description: 'The peak body representing Sikh Australians, organising gurdwara events, community service, and advocacy.',
    imageUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=400',
    city: 'Sydney',
    country: 'Australia',
    rating: 4.9,
    membersCount: 18500,
    ownerId: 'seed-org-13',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Chinese Community Social Services Centre',
    entityType: 'community',
    description: 'Providing bilingual community services, events, and cultural programs to the Chinese-Australian community.',
    imageUrl: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=400',
    city: 'Sydney',
    country: 'Australia',
    rating: 4.7,
    membersCount: 34000,
    ownerId: 'seed-org-5',
    verified: true,
    isSponsored: false,
  },

  // ── Businesses (with sponsorship tiers for directory)
  {
    name: 'Chatkazz — Pakistani & Indian Cuisine',
    entityType: 'business',
    description: 'Authentic halal Pakistani and Indian street food in Harris Park. Known for biryani, seekh kebabs, and the best pani puri in Sydney.',
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    city: 'Sydney',
    country: 'Australia',
    address: '102 Wigram St, Harris Park NSW 2150',
    phone: '+61 2 9635 5888',
    rating: 4.8,
    category: 'restaurant',
    openingHours: 'Tue–Sun 11 AM – 10 PM',
    ownerId: 'seed-biz-1',
    verified: true,
    isSponsored: true,
    sponsorTier: 'gold',
  },
  {
    name: 'Desi Nights Sydney',
    entityType: 'business',
    description: "Sydney's premier South Asian events company. Monthly Bollywood nights, private events, and cultural celebrations since 2018.",
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    city: 'Sydney',
    country: 'Australia',
    phone: '+61 400 123 456',
    rating: 4.5,
    category: 'events',
    ownerId: 'seed-org-3',
    verified: true,
    isSponsored: true,
    sponsorTier: 'silver',
  },
  {
    name: 'Lakemba Bakehouse — Lebanese Sweets',
    entityType: 'business',
    description: 'Family-owned Lebanese pastry shop in Lakemba, famous for baklava, knafeh, and fresh-baked manaqeesh. Est. 1987.',
    imageUrl: 'https://images.unsplash.com/photo-1586985289688-ca3cf47d3e6e?w=400',
    city: 'Sydney',
    country: 'Australia',
    address: '77 Haldon St, Lakemba NSW 2195',
    phone: '+61 2 9759 2121',
    rating: 4.9,
    category: 'bakery',
    openingHours: 'Daily 7 AM – 9 PM',
    ownerId: 'seed-biz-3',
    verified: true,
    isSponsored: true,
    sponsorTier: 'bronze',
  },
  {
    name: 'Pho Thanh — Melbourne Vietnamese',
    entityType: 'business',
    description: 'Authentic Vietnamese pho and bun bo hue in Springvale. A Melbourne institution serving the community for over 30 years.',
    imageUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    city: 'Melbourne',
    country: 'Australia',
    address: '45 Springvale Rd, Springvale VIC 3171',
    rating: 4.7,
    category: 'restaurant',
    openingHours: 'Daily 8 AM – 9 PM',
    ownerId: 'seed-biz-4',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'The Indian Spice House',
    entityType: 'business',
    description: 'Largest Indian grocery and spice importer in Melbourne. Fresh produce, specialty flours, and rare spices from across the Indian subcontinent.',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    city: 'Melbourne',
    country: 'Australia',
    address: '132 Sydney Rd, Brunswick VIC 3056',
    phone: '+61 3 9380 4567',
    rating: 4.6,
    category: 'grocery',
    openingHours: 'Mon–Sat 9 AM – 7 PM',
    ownerId: 'seed-biz-5',
    verified: true,
    isSponsored: true,
    sponsorTier: 'silver',
  },

  // ── Venues
  {
    name: 'Carriageworks',
    entityType: 'venue',
    description: "Sydney's leading multi-arts centre in the historic Eveleigh railway workshops, hosting over 800 events per year including cultural, fashion, and community events.",
    imageUrl: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    city: 'Sydney',
    country: 'Australia',
    address: '245 Wilson St, Eveleigh NSW 2015',
    website: 'https://carriageworks.com.au',
    phone: '+61 2 8571 9999',
    rating: 4.9,
    capacity: 3000,
    ownerId: 'seed-venue-1',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Federation Square',
    entityType: 'venue',
    description: "Melbourne's cultural heart — home to NGV Australia, ACMI, and over 2,000 events per year including Diwali, Holi, and Moomba Festival.",
    imageUrl: 'https://images.unsplash.com/photo-1548681528-6a5c45b66063?w=400',
    city: 'Melbourne',
    country: 'Australia',
    address: 'Cnr Flinders & Swanston St, Melbourne VIC 3000',
    website: 'https://fedsquare.com',
    rating: 4.8,
    capacity: 10000,
    ownerId: 'seed-venue-2',
    verified: true,
    isSponsored: false,
  },

  // ── More Businesses
  {
    name: 'Adelaide Central Market Traders Association',
    entityType: 'business',
    description: "One of the Southern Hemisphere's largest produce markets, with 70+ multicultural traders selling fresh food, spices, and specialties from around the world.",
    imageUrl: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=400',
    city: 'Adelaide',
    country: 'Australia',
    address: '44-60 Gouger St, Adelaide SA 5000',
    website: 'https://adelaidecentralmarket.com.au',
    phone: '+61 8 8203 7494',
    rating: 4.9,
    category: 'market',
    openingHours: 'Tue 7 AM – 5:30 PM, Thu–Fri 9 AM – 5:30 PM, Sat 7 AM – 3 PM',
    ownerId: 'seed-biz-6',
    verified: true,
    isSponsored: true,
    sponsorTier: 'platinum',
  },
  {
    name: 'Perth Indian Superstore',
    entityType: 'business',
    description: 'Western Australia\'s largest Indian and South Asian grocery store in Beckenham, stocking 5,000+ products including fresh produce, spices, snacks, and religious supplies.',
    imageUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=400',
    city: 'Perth',
    country: 'Australia',
    address: '106 Brixton St, Beckenham WA 6107',
    phone: '+61 8 9358 1234',
    rating: 4.7,
    category: 'grocery',
    openingHours: 'Daily 9 AM – 8 PM',
    ownerId: 'seed-biz-7',
    verified: true,
    isSponsored: true,
    sponsorTier: 'gold',
  },
  {
    name: 'Hellenic Club of Sydney',
    entityType: 'business',
    description: "Sydney's premier Greek social and cultural club, offering authentic Greek cuisine, live Bouzouki music, function rooms, and a community gathering space for 80+ years.",
    imageUrl: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400',
    city: 'Sydney',
    country: 'Australia',
    address: '15-17 Loftus St, Sydney NSW 2000',
    phone: '+61 2 9247 2166',
    rating: 4.6,
    category: 'restaurant',
    openingHours: 'Mon–Fri 11 AM – 11 PM, Sat–Sun 10 AM – 11 PM',
    ownerId: 'seed-biz-8',
    verified: true,
    isSponsored: true,
    sponsorTier: 'silver',
  },
  {
    name: 'Yarraka Bayles — Aboriginal Art Gallery',
    entityType: 'business',
    description: 'Award-winning Aboriginal art gallery in Brisbane showcasing dot paintings, bark art, and contemporary works from over 50 First Nations artists across Queensland.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400',
    city: 'Brisbane',
    country: 'Australia',
    address: '192 Boundary St, West End QLD 4101',
    phone: '+61 7 3846 9000',
    rating: 4.9,
    category: 'gallery',
    openingHours: 'Tue–Sun 10 AM – 5 PM',
    ownerId: 'seed-biz-9',
    verified: true,
    isSponsored: true,
    sponsorTier: 'gold',
  },
  {
    name: 'Pacific Island Foods — Brisbane',
    entityType: 'business',
    description: 'The largest Pacific Islander specialty grocery and deli in Queensland, supplying authentic Samoan, Tongan, Fijian, and Cook Islands foods to the community.',
    imageUrl: 'https://images.unsplash.com/photo-1516912481808-3406841bd33c?w=400',
    city: 'Brisbane',
    country: 'Australia',
    address: '88 Zillmere Rd, Boondall QLD 4034',
    rating: 4.5,
    category: 'grocery',
    openingHours: 'Mon–Sat 8 AM – 7 PM',
    ownerId: 'seed-biz-10',
    verified: true,
    isSponsored: false,
  },
  {
    name: 'Korean BBQ Palace — Melbourne',
    entityType: 'business',
    description: "Melbourne's most beloved Korean BBQ restaurant in Springvale, serving premium tabletop BBQ, bibimbap, and Korean fried chicken in a lively communal setting.",
    imageUrl: 'https://images.unsplash.com/photo-1517760444937-f6397edcbbcd?w=400',
    city: 'Melbourne',
    country: 'Australia',
    address: '267 Springvale Rd, Springvale VIC 3171',
    phone: '+61 3 9546 7890',
    rating: 4.8,
    category: 'restaurant',
    openingHours: 'Daily 12 PM – 11 PM',
    ownerId: 'seed-biz-11',
    verified: true,
    isSponsored: true,
    sponsorTier: 'bronze',
  },
  {
    name: 'Spice Route — Canberra Indian Cuisine',
    entityType: 'business',
    description: "Canberra's favourite Indian restaurant in Dickson, serving North and South Indian cuisine with a tandoor oven and one of Australia's best mango lassi selections.",
    imageUrl: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=400',
    city: 'Canberra',
    country: 'Australia',
    address: '47 Woolley St, Dickson ACT 2602',
    rating: 4.7,
    category: 'restaurant',
    openingHours: 'Tue–Sun 11:30 AM – 2:30 PM & 5:30 PM – 10 PM',
    ownerId: 'seed-biz-12',
    verified: true,
    isSponsored: false,
  },

  // ── Artists
  {
    name: 'Bangarra Dance Theatre',
    entityType: 'artist',
    description: 'Australia\'s pre-eminent First Nations performing arts organisation, creating dance works that share Aboriginal and Torres Strait Islander culture with the world.',
    imageUrl: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?w=400',
    city: 'Sydney',
    country: 'Australia',
    website: 'https://bangarra.com.au',
    rating: 5.0,
    followersCount: 48000,
    ownerId: 'seed-artist-1',
    verified: true,
    isSponsored: false,
    tags: ['First Nations', 'Dance', 'Theatre'],
  },
  {
    name: 'Kavisha Mazzella',
    entityType: 'artist',
    description: 'Italian-Australian singer-songwriter weaving together Neapolitan folk traditions with contemporary Australian sound. ARIA Award winner.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    city: 'Melbourne',
    country: 'Australia',
    rating: 4.7,
    followersCount: 12000,
    ownerId: 'seed-artist-2',
    verified: true,
    isSponsored: false,
    tags: ['Italian', 'Folk', 'Singer-Songwriter'],
  },
  {
    name: 'Barkaa',
    entityType: 'artist',
    description: 'Malyangapa and Barkindji rapper and activist from Western NSW. A fearless voice for First Nations justice and community, with a rapidly growing international profile.',
    imageUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400',
    city: 'Sydney',
    country: 'Australia',
    rating: 4.9,
    followersCount: 31000,
    ownerId: 'seed-artist-3',
    verified: true,
    isSponsored: false,
    tags: ['First Nations', 'Hip-Hop', 'Aboriginal'],
  },
  {
    name: 'Usman Riaz',
    entityType: 'artist',
    description: 'Pakistani-Australian composer and multi-instrumentalist blending classical Pakistani music with ambient electronic soundscapes. Performed at TED Global.',
    imageUrl: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
    city: 'Melbourne',
    country: 'Australia',
    rating: 4.8,
    followersCount: 18000,
    ownerId: 'seed-artist-4',
    verified: true,
    isSponsored: false,
    tags: ['Pakistani', 'Classical', 'Fusion'],
  },
] as const;

// ---------------------------------------------------------------------------
// Perks
// ---------------------------------------------------------------------------

const PERKS = [
  {
    title: '20% Off Partner Cafes & Restaurants',
    description: 'Save at 50+ CulturePass partner restaurants across Sydney, Melbourne, and Brisbane. Just show your CulturePass ID.',
    perkType: 'discount_percent',
    discountPercent: 20,
    discountFixedCents: null,
    providerType: 'network',
    providerId: 'seed-org-cafe',
    providerName: 'CulturePass Dining Network',
    category: 'dining',
    isMembershipRequired: false,
    requiredMembershipTier: 'free',
    usageLimit: 2000,
    usedCount: 0,
    perUserLimit: 2,
    status: 'active',
    startDate: now,
    endDate: null,
  },
  {
    title: 'VIP Priority Entry at Cultural Events',
    description: 'Skip the queue at 100+ participating CulturePass events. Includes priority lane access and a complimentary welcome drink.',
    perkType: 'vip_upgrade',
    discountPercent: null,
    discountFixedCents: null,
    providerType: 'event',
    providerId: 'seed-org-events',
    providerName: 'CulturePass Events',
    category: 'events',
    isMembershipRequired: true,
    requiredMembershipTier: 'plus',
    usageLimit: null,
    usedCount: 0,
    perUserLimit: 1,
    status: 'active',
    startDate: now,
    endDate: null,
  },
  {
    title: '$10 Off Festival Tickets',
    description: 'Instant $10 discount on any CulturePass-partnered cultural festival. Applied automatically at checkout.',
    perkType: 'discount_fixed',
    discountPercent: null,
    discountFixedCents: 1000,
    providerType: 'event',
    providerId: 'seed-org-festival',
    providerName: 'Festival Partners AU',
    category: 'events',
    isMembershipRequired: true,
    requiredMembershipTier: 'plus',
    usageLimit: 1000,
    usedCount: 0,
    perUserLimit: 3,
    status: 'active',
    startDate: now,
    endDate: null,
  },
  {
    title: 'Free Community Class (First Time)',
    description: 'Your first community class — language, dance, cooking — at any CulturePass partner is on us. Redeemable once per member.',
    perkType: 'free_ticket',
    discountPercent: null,
    discountFixedCents: null,
    providerType: 'community',
    providerId: 'seed-org-community',
    providerName: 'CulturePass Community Partners',
    category: 'community',
    isMembershipRequired: false,
    requiredMembershipTier: 'free',
    usageLimit: 500,
    usedCount: 0,
    perUserLimit: 1,
    status: 'active',
    startDate: now,
    endDate: null,
  },
  {
    title: '10% Cashback on Event Tickets',
    description: 'Get 10% back in CulturePass credits on all event tickets purchased in-app. Credits applied within 48 hours of the event.',
    perkType: 'cashback',
    discountPercent: 10,
    discountFixedCents: null,
    providerType: 'platform',
    providerId: 'culturepass',
    providerName: 'CulturePass',
    category: 'events',
    isMembershipRequired: true,
    requiredMembershipTier: 'elite',
    usageLimit: null,
    usedCount: 0,
    perUserLimit: null,
    status: 'active',
    startDate: now,
    endDate: null,
  },
] as const;

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

async function clearCollection(name: string) {
  const snap = await db.collection(name).limit(500).get();
  if (snap.empty) return;
  const batch = db.batch();
  snap.docs.forEach((d) => batch.delete(d.ref));
  await batch.commit();
  console.log(`  Cleared ${snap.docs.length} docs from ${name}/`);
}

// ---------------------------------------------------------------------------
// Main seed function
// ---------------------------------------------------------------------------

async function seed() {
  console.log(`\nSeeding Firestore project: ${PROJECT_ID}`);
  console.log('─'.repeat(60));

  if (CLEAR) {
    console.log('\nClearing existing data...');
    for (const col of ['events', 'profiles', 'perks', 'traditionalLands', 'indigenousSpotlights']) {
      await clearCollection(col);
    }
  }

  // Seed events
  console.log('\nSeeding events...');
  const eventsBatch = db.batch();
  for (const event of EVENTS) {
    const ref = db.collection('events').doc();
    eventsBatch.set(ref, { ...event, id: ref.id, createdAt: now, updatedAt: now });
    console.log(`  + ${event.title} (${event.city}, ${event.country})`);
  }
  await eventsBatch.commit();
  console.log(`  ✓ ${EVENTS.length} events seeded`);

  // Seed profiles (communities, businesses, venues, artists)
  console.log('\nSeeding profiles...');
  const profilesBatch = db.batch();
  for (const profile of PROFILES) {
    const ref = db.collection('profiles').doc();
    profilesBatch.set(ref, { ...profile, id: ref.id, createdAt: now, updatedAt: now });
    console.log(`  + [${profile.entityType}] ${profile.name}`);
  }
  await profilesBatch.commit();
  console.log(`  ✓ ${PROFILES.length} profiles seeded`);

  // Seed perks
  console.log('\nSeeding perks...');
  const perksBatch = db.batch();
  for (const perk of PERKS) {
    const ref = db.collection('perks').doc();
    perksBatch.set(ref, { ...perk, id: ref.id, createdAt: now });
    console.log(`  + ${perk.title}`);
  }
  await perksBatch.commit();
  console.log(`  ✓ ${PERKS.length} perks seeded`);

  // Seed traditional lands
  console.log('\nSeeding traditional lands...');
  const landsBatch = db.batch();
  for (const land of TRADITIONAL_LANDS) {
    const ref = db.collection('traditionalLands').doc(land.id);
    landsBatch.set(ref, { ...land, createdAt: now });
    console.log(`  + ${land.city} — ${land.landName}`);
  }
  await landsBatch.commit();
  console.log(`  ✓ ${TRADITIONAL_LANDS.length} traditional lands seeded`);

  // Seed indigenous spotlights
  console.log('\nSeeding Indigenous spotlights...');
  const spotlightsBatch = db.batch();
  for (const spotlight of INDIGENOUS_SPOTLIGHTS) {
    const ref = db.collection('indigenousSpotlights').doc(spotlight.id);
    spotlightsBatch.set(ref, { ...spotlight, createdAt: now });
    console.log(`  + ${spotlight.title}`);
  }
  await spotlightsBatch.commit();
  console.log(`  ✓ ${INDIGENOUS_SPOTLIGHTS.length} spotlights seeded`);

  console.log('\n✅ Firestore seed complete!\n');
  console.log('Collections seeded:');
  console.log('  events           →', EVENTS.length, 'events across 7 cities and 6 regions');
  console.log('  profiles         →', PROFILES.length, 'communities, businesses, venues, artists');
  console.log('  perks            →', PERKS.length, 'perks');
  console.log('  traditionalLands →', TRADITIONAL_LANDS.length, 'First Nations/Māori land acknowledgements');
  console.log('  indigenousSpotlights →', INDIGENOUS_SPOTLIGHTS.length, 'First Nations spotlights');
  console.log('\nNext steps:');
  console.log('  1. Run: firebase deploy --only functions');
  console.log('  2. Run: firebase deploy --only firestore:rules,firestore:indexes');
  console.log('  3. Test: curl https://us-central1-culturepass-4f264.cloudfunctions.net/api/events\n');
}

seed().catch((err) => {
  console.error('\n❌ Seed failed:', err.message ?? err);
  process.exit(1);
});
