/**
 * Host Module Services
 * 
 * Exports all services for the HostSpace Enterprise-Grade Form System.
 */

export {
  serializeFormData,
  deserializeFormData,
  mergeFormData,
  calculateFormDiff,
  validateFormDataStructure,
  type PartialFormData,
  type SerializationOptions,
} from './formStateSerializer';

export {
  generateProfileSEO,
  generateMetaTitle,
  generateMetaDescription,
  generateCanonicalUrl,
  generateOpenGraphTags,
  generateTwitterCardTags,
  generateJsonLd,
  generateSitemapEntry,
  generateSitemapXml,
  generateHeadingHierarchy,
  generateImageAltTexts,
  generateImageAlt,
  generateRobotsDirective,
  generateRobotsTxt,
  stripHtmlTags,
  truncateAtWord,
  type SEOEntityType,
  type SEOProfileData,
  type ProfileSEOMeta,
  type OpenGraphMeta,
  type TwitterCardMeta,
  type JsonLdData,
  type HeadingHierarchy,
  type ImageAltText,
  type SitemapEntry,
} from './seoService';

export {
  triggerProfileNotification,
  triggerProfilePublished,
  triggerVerificationStatusChange,
  triggerLicenceExpiryReminder,
  triggerEngagementMilestone,
  triggerPerformanceDecline,
  checkMilestoneReached,
  checkLicenceExpiry,
  getDefaultPreferences,
  getActiveChannels,
  shouldBatchToDigest,
  isWithinQuietHours,
  getEventLabel,
  getEventDescription,
  ENGAGEMENT_MILESTONES,
  LICENCE_EXPIRY_REMINDER_DAYS,
  DEFAULT_NOTIFICATION_PREFERENCES,
  type NotificationChannel,
  type ProfileNotificationEvent,
  type EngagementMilestone,
  type NotificationTriggerPayload,
  type NotificationPreference,
  type HostNotificationPreferences,
} from './notificationTriggers';

export {
  getProfilePrivacySettings,
  updateProfilePrivacySettings,
  setFieldPrivacy,
  exportProfileData,
  downloadExportedData,
  requestDataDeletion,
  cancelDataDeletion,
  isSensitiveField,
  maskSensitiveValue,
  logFieldAccess,
  createConsentRecord,
  validateRequiredConsents,
  getPrivacyPolicyUrl,
  DEFAULT_FIELD_PRIVACY,
  SENSITIVE_FIELDS,
  REQUIRED_CONSENTS,
  OPTIONAL_CONSENTS,
  PRIVACY_POLICY_URL,
  TERMS_OF_SERVICE_URL,
  type FieldPrivacySettings,
  type ProfilePrivacyConfig,
  type ConsentRecord,
  type DataExportPayload,
  type AccessLogEntry,
  type DataDeletionRequest,
  type SensitiveField,
} from './privacyService';

export {
  trackFormSessionStarted,
  trackStepStarted,
  trackStepCompleted,
  trackFormAbandoned,
  trackFormSubmitted,
  trackValidationError,
  trackAutoSave,
  trackApiCall,
  trackUpload,
  trackAIAssistUsage,
  trackHelpClick,
  trackAlertTriggered,
  resetSessionCounters,
  getSessionMetrics,
  getDeviceInfo,
  generateSessionId,
  ERROR_RATE_THRESHOLD,
  RESPONSE_TIME_THRESHOLD_MS,
  AUTO_SAVE_FAILURE_THRESHOLD,
  ERROR_RATE_WINDOW_MS,
  type WizardStep,
  type FormEntityType,
  type AutoSaveStatus,
  type UploadStatus,
  type AlertSeverity,
  type DeviceInfo,
  type FormSessionContext,
  type StepTiming,
  type ValidationErrorEntry,
  type ApiTimingEntry,
  type AIAssistUsageEntry,
} from './formAnalyticsService';
