/**
 * HostSpace Create Lab — category catalog and group filters.
 */
import { Ionicons } from '@expo/vector-icons';
import { CultureTokens } from '@/design-system/tokens/theme';
import type { ListingWizardEntityParam } from '@/constants/navigation/experienceNav';
import { CREATE_LAB_PATHNAME, createLabCategoryHref } from '@/constants/navigation/createNav';

export type CategoryGroup = 'all' | 'venues' | 'businesses' | 'communities' | 'events' | 'market';
export type CreateContentKind = 'event' | 'activity' | 'offer' | 'market' | 'listing';

export type CreateCategory = {
  id: string;
  aliases: string[];
  label: string;
  route: string;
  browseRoute: string;
  type: 'Creation';
  purpose: string;
  description: string;
  icon: keyof typeof Ionicons.glyphMap;
  color: string;
  entityType: ListingWizardEntityParam;
  group: CategoryGroup;
  kind?: 'owner' | 'content';
  contentKind?: CreateContentKind;
  requiresParent?: boolean;
  subCategory?: string;
};

export const CREATE_CATEGORIES: CreateCategory[] = [
  // ── Communities & Orgs ───────────────────────────────────────────────────
  {
    id: 'community',
    aliases: ['communities'],
    label: 'Community',
    route: createLabCategoryHref('community'),
    browseRoute: '/(tabs)/community',
    type: 'Creation',
    purpose: 'Create new communities',
    description: 'Launch a diaspora group, cultural association, or member community.',
    icon: 'people-outline',
    color: CultureTokens.teal,
    entityType: 'community',
    group: 'communities',
  },
  {
    id: 'organizer',
    aliases: ['organiser', 'organizers', 'organisers', 'producer'],
    label: 'Organizer',
    route: createLabCategoryHref('organizer'),
    browseRoute: '/hostspace/dashboard',
    type: 'Creation',
    purpose: 'Organizer profiles',
    description: 'Create the producing brand behind festivals, series, venues, and ticketing.',
    icon: 'flag-outline',
    color: CultureTokens.indigo,
    entityType: 'organizer',
    group: 'communities',
  },
  {
    id: 'association',
    aliases: ['associations', 'cultural-association', 'member-association'],
    label: 'Association',
    route: createLabCategoryHref('association'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Cultural and member associations',
    description: 'Register associations that manage members, programs, events, and community services.',
    icon: 'people-circle-outline',
    color: CultureTokens.teal,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'association',
  },
  {
    id: 'organisation',
    aliases: ['organization', 'organizations', 'organisations', 'ngo', 'nonprofit', 'non-profit'],
    label: 'Organisation',
    route: createLabCategoryHref('organisation'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Non-profit and civic organisations',
    description: 'Register cultural societies, diaspora bodies, and non-profit organisations.',
    icon: 'business-outline',
    color: CultureTokens.indigo,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'organisation',
  },
  {
    id: 'ngo',
    aliases: ['ngos', 'non-government', 'non-government-organisation', 'non-government-organization'],
    label: 'NGO',
    route: createLabCategoryHref('ngo'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'NGOs and community services',
    description: 'Create non-government organisations, service providers, and community advocacy bodies.',
    icon: 'ribbon-outline',
    color: CultureTokens.violet,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'ngo',
  },
  {
    id: 'charity',
    aliases: ['charities', 'foundation', 'ngo'],
    label: 'Charity',
    route: createLabCategoryHref('charity'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Charities and foundations',
    description: 'Add charitable foundations, community benefit organisations, and causes.',
    icon: 'heart-outline',
    color: CultureTokens.coral,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'charity',
  },
  {
    id: 'government',
    aliases: ['gov', 'governmental', 'public-sector'],
    label: 'Government',
    route: createLabCategoryHref('government'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Government and public sector',
    description: 'Add government agencies, embassies, consulates, and public services.',
    icon: 'shield-checkmark-outline',
    color: CultureTokens.indigo,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'government',
  },
  {
    id: 'council',
    aliases: ['councils', 'lga', 'local-government', 'municipal'],
    label: 'Council',
    route: createLabCategoryHref('council'),
    browseRoute: '/my-council',
    type: 'Creation',
    purpose: 'Local government and councils',
    description: 'Register a council, LGA, or municipal body for proximity services.',
    icon: 'map-outline',
    color: CultureTokens.teal,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'council',
  },
  {
    id: 'club-society',
    aliases: ['club', 'clubs', 'society', 'societies', 'student-club', 'social-club'],
    label: 'Club or Society',
    route: createLabCategoryHref('club-society'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Clubs and societies',
    description: 'Create clubs, societies, student groups, alumni circles, and interest-based cultural groups.',
    icon: 'sparkles-outline',
    color: CultureTokens.gold,
    entityType: 'organizer',
    group: 'communities',
    subCategory: 'club_society',
  },

  // ── Venues & Spaces ──────────────────────────────────────────────────────
  {
    id: 'venue',
    aliases: ['venues', 'space', 'hall'],
    label: 'Venue',
    route: createLabCategoryHref('venue'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Add venues',
    description: 'Create halls, galleries, clubs, theatres, and cultural spaces.',
    icon: 'location-outline',
    color: CultureTokens.teal,
    entityType: 'venue',
    group: 'venues',
  },
  {
    id: 'dance-studio',
    aliases: ['dance', 'dance-school', 'dance-company'],
    label: 'Dance Studio',
    route: createLabCategoryHref('dance-studio'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Dance studios and companies',
    description: 'Register dance schools, Bollywood studios, Bharatanatyam academies, and dance companies.',
    icon: 'body-outline',
    color: CultureTokens.coral,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'dance',
  },
  {
    id: 'art-gallery',
    aliases: ['art', 'gallery', 'art-space', 'exhibition-space'],
    label: 'Art Gallery',
    route: createLabCategoryHref('art-gallery'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Galleries and art spaces',
    description: 'Add galleries, artist studios, cultural exhibition spaces, and creative hubs.',
    icon: 'color-palette-outline',
    color: CultureTokens.coral,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'art',
  },
  {
    id: 'cinema',
    aliases: ['movies', 'theatre', 'film', 'movie-theatre'],
    label: 'Cinema',
    route: createLabCategoryHref('cinema'),
    browseRoute: '/movies',
    type: 'Creation',
    purpose: 'Cinemas and screening venues',
    description: 'Register cinemas, film clubs, screening rooms, and film societies.',
    icon: 'film-outline',
    color: CultureTokens.indigo,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'cinema',
  },
  {
    id: 'nightlife',
    aliases: ['nightclub', 'club', 'bar', 'lounge'],
    label: 'Nightlife',
    route: createLabCategoryHref('nightlife'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Clubs, bars, and nightlife venues',
    description: 'Add clubs, cocktail bars, rooftop lounges, and late-night cultural venues.',
    icon: 'moon-outline',
    color: CultureTokens.violet,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'nightlife',
  },
  {
    id: 'comedy-club',
    aliases: ['comedy', 'stand-up', 'improv'],
    label: 'Comedy Club',
    route: createLabCategoryHref('comedy-club'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Comedy clubs and theatres',
    description: 'Register comedy clubs, stand-up venues, and improv theatre spaces.',
    icon: 'happy-outline',
    color: CultureTokens.gold,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'comedy',
  },
  {
    id: 'sports-venue',
    aliases: ['sports', 'stadium', 'gym', 'recreation', 'sports-club'],
    label: 'Sports Venue',
    route: createLabCategoryHref('sports-venue'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Sports venues and recreation centres',
    description: 'Add stadiums, gyms, sports clubs, cricket grounds, and recreation centres.',
    icon: 'football-outline',
    color: CultureTokens.teal,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'sports',
  },
  {
    id: 'monument',
    aliases: ['monuments', 'landmark', 'attractions', 'heritage-site', 'cultural-site'],
    label: 'Monument',
    route: createLabCategoryHref('monument'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Monuments and cultural landmarks',
    description: 'Register heritage sites, monuments, cultural landmarks, and points of interest.',
    icon: 'earth-outline',
    color: CultureTokens.gold,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'monument',
  },
  {
    id: 'wellness-space',
    aliases: ['spa', 'yoga-studio', 'meditation-centre', 'retreat-centre'],
    label: 'Wellness Space',
    route: createLabCategoryHref('wellness-space'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Wellness studios and retreat spaces',
    description: 'Add yoga studios, meditation centres, spas, and wellness retreat venues.',
    icon: 'leaf-outline',
    color: CultureTokens.teal,
    entityType: 'venue',
    group: 'venues',
    subCategory: 'wellness',
  },

  // ── Businesses & Services ─────────────────────────────────────────────────
  {
    id: 'business',
    aliases: ['businesses', 'company', 'brand'],
    label: 'Business',
    route: createLabCategoryHref('business'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Register businesses',
    description: 'Add shops, services, producers, and cultural brands to the directory.',
    icon: 'briefcase-outline',
    color: CultureTokens.indigo,
    entityType: 'business',
    group: 'businesses',
  },
  {
    id: 'dining',
    aliases: ['dine', 'food', 'restaurant', 'restaurants', 'cafe', 'eatery'],
    label: 'Dining',
    route: createLabCategoryHref('dining'),
    browseRoute: '/restaurants',
    type: 'Creation',
    purpose: 'Restaurant and food profiles',
    description: 'Create a restaurant, café, or food business profile with menus and delivery notes.',
    icon: 'restaurant-outline',
    color: CultureTokens.coral,
    entityType: 'restaurant',
    group: 'events',
    kind: 'content',
    contentKind: 'listing',
    requiresParent: true,
    subCategory: 'dining',
  },
  {
    id: 'artist',
    aliases: ['artists', 'performer', 'musician', 'creator'],
    label: 'Artist',
    route: createLabCategoryHref('artist'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Artist profiles',
    description: 'Create performer, maker, speaker, and creative profiles for line-ups.',
    icon: 'mic-outline',
    color: CultureTokens.coral,
    entityType: 'artist',
    group: 'businesses',
  },
  {
    id: 'shopping',
    aliases: ['shop', 'shops', 'retail', 'store'],
    label: 'Shopping',
    route: createLabCategoryHref('shopping'),
    browseRoute: '/shopping',
    type: 'Creation',
    purpose: 'Retail and shopping profiles',
    description: 'Create a shop, maker market, or cultural retail business profile.',
    icon: 'bag-handle-outline',
    color: CultureTokens.teal,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'market',
    requiresParent: true,
    subCategory: 'shopping',
  },
  {
    id: 'workshop',
    aliases: ['workshops', 'class', 'classes', 'academy', 'school'],
    label: 'Workshop',
    route: createLabCategoryHref('workshop'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Workshop providers and educators',
    description: 'Add cooking schools, language academies, craft workshops, and skill providers.',
    icon: 'construct-outline',
    color: CultureTokens.gold,
    entityType: 'business',
    group: 'businesses',
    subCategory: 'workshop',
  },
  {
    id: 'wellness',
    aliases: ['wellness-business', 'health', 'holistic', 'ayurveda'],
    label: 'Wellness Business',
    route: createLabCategoryHref('wellness'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Wellness and health businesses',
    description: 'Register Ayurvedic clinics, holistic health providers, and wellness brands.',
    icon: 'fitness-outline',
    color: CultureTokens.teal,
    entityType: 'business',
    group: 'businesses',
    subCategory: 'wellness_business',
  },

  // ── Content created under a verified owner profile ────────────────────────
  {
    id: 'event',
    aliases: ['events', 'festival', 'concert', 'show'],
    label: 'Event',
    route: createLabCategoryHref('event'),
    browseRoute: '/(domain)/events',
    type: 'Creation',
    purpose: 'Create events under a host profile',
    description: 'Publish free or ticketed events under a community, association, organisation, business, venue, charity, council, club, or society.',
    icon: 'calendar-outline',
    color: CultureTokens.coral,
    entityType: 'event',
    group: 'events',
    kind: 'content',
    contentKind: 'event',
    requiresParent: true,
  },
  {
    id: 'art',
    aliases: ['arts', 'gallery-listing', 'exhibition', 'creative'],
    label: 'Art',
    route: createLabCategoryHref('art'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Create art listings',
    description: 'Add exhibitions, creative programs, art services, and cultural art listings under a verified host profile.',
    icon: 'color-palette-outline',
    color: CultureTokens.violet,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'listing',
    requiresParent: true,
    subCategory: 'art',
  },
  {
    id: 'movie',
    aliases: ['movies', 'film', 'films', 'screening'],
    label: 'Movie',
    route: createLabCategoryHref('movie'),
    browseRoute: '/movies',
    type: 'Creation',
    purpose: 'Create movie and screening listings',
    description: 'Add film screenings, movie programs, cinema offers, and community screenings under a verified host profile.',
    icon: 'film-outline',
    color: CultureTokens.indigo,
    entityType: 'venue',
    group: 'events',
    kind: 'content',
    contentKind: 'listing',
    requiresParent: true,
    subCategory: 'movie',
  },
  {
    id: 'activity',
    aliases: ['activities', 'experience', 'experiences', 'class'],
    label: 'Activity',
    route: createLabCategoryHref('activity'),
    browseRoute: '/activities',
    type: 'Creation',
    purpose: 'Create activities and experiences',
    description: 'Create workshops, classes, tours, and participatory cultural experiences under a verified host profile.',
    icon: 'sparkles-outline',
    color: CultureTokens.teal,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'activity',
    requiresParent: true,
  },
  {
    id: 'travel',
    aliases: ['trip', 'tour', 'tours', 'tourism'],
    label: 'Travel',
    route: createLabCategoryHref('travel'),
    browseRoute: '/activities',
    type: 'Creation',
    purpose: 'Create travel and tour listings',
    description: 'Add tours, retreats, travel experiences, and cultural trips under a verified host profile.',
    icon: 'airplane-outline',
    color: CultureTokens.teal,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'listing',
    requiresParent: true,
    subCategory: 'travel',
  },
  {
    id: 'offer',
    aliases: ['offers', 'deal', 'deals', 'perk', 'perks'],
    label: 'Offer',
    route: createLabCategoryHref('offer'),
    browseRoute: '/offers',
    type: 'Creation',
    purpose: 'Create offers and perks',
    description: 'Publish discounts, member perks, bundles, and limited offers under a verified host profile.',
    icon: 'pricetag-outline',
    color: CultureTokens.gold,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'offer',
    requiresParent: true,
  },
  {
    id: 'other-listing',
    aliases: ['other', 'general-listing', 'listing'],
    label: 'Other Listing',
    route: createLabCategoryHref('other-listing'),
    browseRoute: '/(tabs)/directory',
    type: 'Creation',
    purpose: 'Create another listing type',
    description: 'Create a general cultural listing under a verified host profile when no specialised type fits.',
    icon: 'document-text-outline',
    color: CultureTokens.indigo,
    entityType: 'business',
    group: 'events',
    kind: 'content',
    contentKind: 'listing',
    requiresParent: true,
    subCategory: 'other',
  },

  // ── CultureMarket ─────────────────────────────────────────────────────────
  {
    id: 'market-listing',
    aliases: ['listing', 'marketplace', 'culturemarketplace', 'culturemarket', 'market', 'sell', 'product', 'service'],
    label: 'CultureMarket Listing',
    route: CREATE_LAB_PATHNAME,
    browseRoute: '/CultureMarket',
    type: 'Creation',
    purpose: 'List on CultureMarket',
    description: 'Sell a product, offer a service, or link your cultural business website to reach thousands of diaspora members.',
    icon: 'storefront-outline',
    color: CultureTokens.coral,
    entityType: 'business',
    group: 'market',
  },
  {
    id: 'market-product',
    aliases: ['product', 'sell-product', 'physical', 'digital'],
    label: 'Sell a Product',
    route: CREATE_LAB_PATHNAME,
    browseRoute: '/CultureMarket',
    type: 'Creation',
    purpose: 'Sell physical or digital products',
    description: 'List a physical or digital product for sale — buyers purchase or contact you directly.',
    icon: 'cube-outline',
    color: CultureTokens.coral,
    entityType: 'business',
    group: 'market',
    subCategory: 'product',
  },
  {
    id: 'market-service',
    aliases: ['service', 'offer-service', 'bookable', 'lesson', 'experience'],
    label: 'Offer a Service',
    route: CREATE_LAB_PATHNAME,
    browseRoute: '/CultureMarket',
    type: 'Creation',
    purpose: 'Offer a bookable service or experience',
    description: 'Offer a service, lesson, or cultural experience — set your price and let buyers contact you.',
    icon: 'briefcase-outline',
    color: CultureTokens.teal,
    entityType: 'business',
    group: 'market',
    subCategory: 'service',
  },
  {
    id: 'market-link',
    aliases: ['link', 'website', 'external', 'link-site'],
    label: 'Link Your Website',
    route: CREATE_LAB_PATHNAME,
    browseRoute: '/CultureMarket',
    type: 'Creation',
    purpose: 'Link your cultural business website',
    description: 'Add your business to CultureMarket with a link directly to your own website. Drive traffic and grow your audience.',
    icon: 'open-outline',
    color: CultureTokens.violet,
    entityType: 'business',
    group: 'market',
    subCategory: 'link',
  },
];

export const GROUP_TABS: { id: CategoryGroup; label: string; icon: keyof typeof Ionicons.glyphMap }[] = [
  { id: 'all',          label: 'All',        icon: 'grid-outline'       },
  { id: 'events',       label: 'Content',    icon: 'add-circle-outline' },
  { id: 'market',       label: 'Market',     icon: 'storefront-outline' },
  { id: 'communities',  label: 'Orgs',       icon: 'people-outline'     },
  { id: 'venues',       label: 'Venues',     icon: 'location-outline'   },
  { id: 'businesses',   label: 'Businesses', icon: 'briefcase-outline'  },
];

export const GROUP_COLORS: Record<CategoryGroup, string> = {
  all:         CultureTokens.indigo,
  market:      CultureTokens.coral,
  communities: CultureTokens.teal,
  venues:      CultureTokens.violet,
  businesses:  CultureTokens.coral,
  events:      CultureTokens.gold,
};

function normalizeCategory(raw: string | undefined): string {
  return (raw ?? '').trim().toLowerCase().replace(/^\/+|\/+$/g, '');
}

export function findCategory(raw: string | undefined): CreateCategory {
  const normalized = normalizeCategory(raw);
  return (
    CREATE_CATEGORIES.find((item) => item.id === normalized || item.aliases.includes(normalized)) ??
    CREATE_CATEGORIES[0]
  );
}
